### ISSUE TITLE
Aria2 RPC 不可在radarr中使用

### ISSUE THREAD

**Issue by AhauFun** [wy580477/Leech-AIO-APP-EX#10]
在我自己的radarr服务器中添加该aria2客户端，无法测试成功，不能保存，但在任意AriaNG中都可以连接。希望大神修复。

**Comment by wy580477** [comment]
搞好了。https://github.com/wy580477/Colab-Heroku-AIO-APP-EX/commit/f19865500db65ca686f0c3baf3044a28ed90dea6

比如你的 GLOBAL_PORTAL_PATH 设置为 mypath
重新部署以后，radarr的XML RPC Path项里面填 "/mypath/rpc"。

**Comment by wy580477** [comment]
现在Caddyfile增加了qBit的/api路径反代设置，去掉注释后可以连接到Radarr之类不支持qBit自定义路径的app.

**Comment by fridaycookie** [comment]
> 现在Caddyfile增加了qBit的/api路径反代设置，去掉注释后可以连接到Radarr之类不支持qBit自定义路径的app.

radarr开启高级设置qBit就能添加自定义路径了
![image](https://user-images.githubusercontent.com/101806755/175511398-448b2868-c9e4-46c4-8b3c-bb2bd1ea3e0c.png)

**Comment by wy580477** [comment]
> radarr开启高级设置qBit就能添加自定义路径了 

感谢提醒。
