### ISSUE TITLE
我想替换qBittorrent版本但是出现了错误

### ISSUE THREAD

**Issue by ke-xi** [wy580477/Leech-AIO-APP-EX#104]
<img width="1280" alt="Snipaste_2023-06-15_03-25-28" src="https://github.com/wy580477/Leech-AIO-APP-EX/assets/58284266/f93e3487-8544-483d-805f-59f38309ab42">

<img width="439" alt="Snipaste_2023-06-15_03-25-43" src="https://github.com/wy580477/Leech-AIO-APP-EX/assets/58284266/a2e5d0c1-303f-4ca8-b6b4-28e09fca2fff">

还有其他地方要修改吗?为什么会出现这个报错,还有
https://github.com/ke-xi/waline/releases/download/1/qbittorrent-nox.zip
这个版本可以安装进去吗?

**Comment by wy580477** [comment]
这个报错，是压缩包目录结构不对，找不到解压后的文件了。

![image](https://github.com/wy580477/Leech-AIO-APP-EX/assets/98247050/faff0ca2-62e2-435a-91b5-7c8ae717079d)

**Comment by ke-xi** [comment]
> 这个报错，是压缩包目录结构不对，找不到解压后的文件了。
> 
> ![image](https://user-images.githubusercontent.com/98247050/245958253-faff0ca2-62e2-435a-91b5-7c8ae717079d.png)

是的,是压缩问题,解决了,感谢
