### ISSUE TITLE
Colab Vs Docker (VPS)

### ISSUE THREAD

**Issue by james00000007** [wy580477/Leech-AIO-APP-EX#109]
@wy580477 

since i am useing the Colab deployment long time and there is no issue till date.

while i now create  the  deployment on VPS Via [docker-compose file](https://github.com/wy580477/Leech-AIO-APP-EX/blob/docker/docker-compose_en.yml) 

while i am edit docker-compose_en.yml file below screen shot for your ref. 502 Bad Gateway.shown

domin +/portal 

or try with or VPS IP+port/portal give the below error.

since i nginx proxy manger using the 443 port i can change to different port e.g 8880 or 6000

below screen shot of of nginx proxy manger.

can you please help me in this issue i know i am missing something, as i am not a technical person/developer.

**Comment by wy580477** [comment]
If you are using reserse proxy such as npm, you shoud leave CADDY_DOMAIN blank.

HTTPS is handled by npm , you don't need to set via docker-compose file.

**Comment by wy580477** [comment]
> is there changes need to be done in [Dockerfile](https://github.com/wy580477/Leech-AIO-APP-EX/blob/docker/Dockerfile) ?

No need.

**Comment by wy580477** [comment]
> i set to CADDY_DOMAIN to http://xxx.xxx.eu.org/ but if i removed from [docker-compose file](https://github.com/wy580477/Leech-AIO-APP-EX/blob/docker/docker-compose_en.yml) then how i can access to reach portal page ?

What do you mean by "if i removed from [docker-compose file]"？

**Comment by james00000007** [comment]
i mean the URL remove from docker-compose file and should i http://**ip**:port include. set to CADDY_DOMAIN.

sorry for trouble you.

**Comment by wy580477** [comment]
> i mean the URL remove from docker-compose file and should i http://**ip**:port include. set to CADDY_DOMAIN.
> 
> sorry for trouble you.

I'm confused. 

> i set to CADDY_DOMAIN to http://xxx.xxx.eu.org/

Do you set to a URL or not? Now is your service working?

**Comment by james00000007** [comment]
please refer the screen shot for your ref.
![Screenshot 2023-08-14 101620](https://github.com/wy580477/Leech-AIO-APP-EX/assets/95303830/e1953c27-415d-408d-8073-dbf17c1b7508)

**Comment by wy580477** [comment]
> please refer the screen shot for your ref. ![Screenshot 2023-08-14 101620](https://user-images.githubusercontent.com/95303830/260523923-e1953c27-415d-408d-8073-dbf17c1b7508.png)

I don't use portainer, so can't help you.

**Comment by james00000007** [comment]
> i set to CADDY_DOMAIN to http://xxx.xxx.eu.org/

Yes i set to CADDY_DOMAIN to http://xxx.xxx.eu.org/ in [docker-compose file](https://github.com/wy580477/Leech-AIO-APP-EX/blob/docker/docker-compose_en.yml)

i am deploy via SSh putty

please have look the below
![Screenshot 2023-08-14 102459](https://github.com/wy580477/Leech-AIO-APP-EX/assets/95303830/9a457781-5d70-4767-ad7f-c4d413aa9b53)

**Comment by wy580477** [comment]
？？？
I tell you to set to http:// , why would set to https:// ？？？

Do you have trouble to understand what I said？

**Comment by james00000007** [comment]
> ？？？ I tell you to set to http:// , why would set to https:// ？？？
> 
> Do you have trouble to understand what I said？

it my mistake, correct set to [http://](http://xxx.xxx.eu.org/) and run 

Build Docker image via below command  

sudo docker build . -t leech-aio 

please let me know if anything pending from my end ?

let see if successfully done or not.

**Comment by wy580477** [comment]
> @wy580477
> 
> getting below error.
> 
> ![Screenshot 2023-08-16 085144](https://user-images.githubusercontent.com/95303830/261064532-2741e5a9-005c-4239-8488-b841fe1b2656.png)

This a caddy dependency error which I will fix later.

Why do you need to build your own image? I already provide ready to use image.

**Comment by james00000007** [comment]
![Screenshot 2023-08-16 101011](https://github.com/wy580477/Leech-AIO-APP-EX/assets/95303830/caa51f68-d4c0-49ab-9bf4-12ef420416ec)

Error 502

![Screenshot 2023-08-16 101114](https://github.com/wy580477/Leech-AIO-APP-EX/assets/95303830/cbff7dca-d684-4a83-bb0d-7c233448e58a)

not sure what i am do wrong. i know you are try to tell me every possibility but i am not able to done.

**Comment by james00000007** [comment]
> ![Screenshot 2023-08-16 101011](https://user-images.githubusercontent.com/95303830/261084512-caa51f68-d4c0-49ab-9bf4-12ef420416ec.png)
> 
> Error 502
> 
> ![Screenshot 2023-08-16 101114](https://user-images.githubusercontent.com/95303830/261084556-cbff7dca-d684-4a83-bb0d-7c233448e58a.png)
> 
> not sure what i am do wrong. i know you are try to tell me every possibility but i am not able to done.

finally
![Screenshot 2023-08-16 102710](https://github.com/wy580477/Leech-AIO-APP-EX/assets/95303830/9ca14dfd-9cda-4889-8047-69fe77a324c3)

**Comment by james00000007** [comment]
@wy580477 
can you please removed all the images of this issue conversation

**Comment by james00000007** [comment]
please close this issue,
