### ISSUE TITLE
aria2配置

### ISSUE THREAD

**Issue by vb197701** [wy580477/Leech-AIO-APP-EX#111]
首先感谢大佬的项目，我在配置aria2时，出现RPC请求头，请问怎样配置？谢谢！
![IMG_6530](https://github.com/wy580477/Leech-AIO-APP-EX/assets/120435620/164acdc4-2d22-4e88-a572-c8598cff0ef4)

**Comment by wy580477** [comment]
留空白即可。

另外， 协议可以选 websocket，理论上会快一点。

**Comment by wy580477** [comment]
> 留白的话，链接不上，选websocket，显示重连，都链接不了。

连不上，检查地址栏里面显示的协议和端口，和 地址栏 里面的一样嘛。

**Comment by wy580477** [comment]
> > > 留白的话，链接不上，选websocket，显示重连，都链接不了。
> > 
> > 
> > 连不上，检查浏览器地址栏里面显示的协议和端口，和下面 Aria2 RPC 地址栏 里面的一样嘛。
> 
> 都检查过了，还是不行，郁闷。。。

你把域名/ip 抹掉，整个浏览器截图发出来。

**Comment by wy580477** [comment]
> > > > > 留白的话，链接不上，选websocket，显示重连，都链接不了。
> > > > 
> > > > 
> > > > 连不上，检查浏览器地址栏里面显示的协议和端口，和下面 Aria2 RPC 地址栏 里面的一样嘛。
> > > 
> > > 
> > > 都检查过了，还是不行，郁闷。。。
> > 
> > 
> > 你把域名/ip 抹掉，整个浏览器截图发出来。
> 
> 好的，大佬请看 ![01](https://user-images.githubusercontent.com/120435620/263625999-59e85f2a-923d-49ff-a443-694783826ae9.png)

61800 就不像对的样子，你自己改的？ 默认应该是浏览器地址栏里面的端口。
