### ISSUE TITLE
支持下载m3u8格式的链接

### ISSUE THREAD

**Issue by 1715819** [wy580477/Leech-AIO-APP-EX#112]
尊敬的开发者您好，是否可以增加下载m3u8链接的功能，有现成的二进制程序可以拿来使用
项目：https://github.com/orestonce/m3u8d

如果可以的话，希望能够引入此功能，谢谢！

**Comment by wy580477** [comment]
yt-dlp 支持 m3u8 下载啊，你在 metube 页面把 m3u8 链接填进去应该就可以下载了。

**Comment by 1715819** [comment]
明白了，谢谢
