### ISSUE TITLE
能不能整个浏览器

### ISSUE THREAD

**Issue by gdhdhdh1441414** [wy580477/Leech-AIO-APP-EX#13]
用于解除验证码。

有些视频网站对部署的服务器（heroku、colab）ip有验证码，我想通过浏览器访问视频地址，手动填验证码解除

**Comment by wy580477** [comment]
1. 我猜验证码填完也是cookie授权吧，只对浏览器起作用。
    你可以连接vmess代理，这样浏览器访问就是用部署服务器的ip，我猜是不行的。
    解决方法应该可能还是给yt-dlp指定cookie选项。

2. 桌面环境相关软件包是Heroku严打范围，部署完必封号。
