### ISSUE TITLE
Can't delete excluded files!

### ISSUE THREAD

**Issue by vtstojs** [wy580477/Leech-AIO-APP-EX#15]
Hi bro ,I have set min-size=60M in script.conf file ,but it can't delete excluded files automatically after downloading torrent tasks.
Here are some info in log/aria2/current:
![delete](https://user-images.githubusercontent.com/103717184/171862830-96c5ff93-30b4-49f3-9f7f-ec7101d28807.jpg)

**Comment by wy580477** [comment]
I will take a look tomorrow.

Perhaps this function needs "real" find command instead of built-in one in busybox.

**Comment by vtstojs** [comment]
ok, it could delete excluded files before you added pyload .Have a good night ,bro!

**Comment by wy580477** [comment]
> ok, it could delete excluded files before you added pyload .Have a good night ,bro!

Now I think it's definitely the find command issue. I remove find-utils package when I added pyload.

Turn out that original script author requires find-utils for a reason.

**Comment by wy580477** [comment]
https://github.com/wy580477/Leech-AIO-APP-EX/commit/4791ad7b2d759b9867830935070ce3f21722a37a

Fixed.
