### ISSUE TITLE
rclone setup

### ISSUE THREAD

**Issue by arjung24** [wy580477/Leech-AIO-APP-EX#18]
my rclone setup showing following error

[youtube] t0Q2otsqC4I: Downloading webpage
[youtube] t0Q2otsqC4I: Downloading android player API JSON
[info] t0Q2otsqC4I: Downloading 1 format(s): 248+251
[download] Destination: /mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].f248.webm
[download] Download completed
[download] Destination: /mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].f251.webm
[download] Download completed
[Merger] Merging formats into "/mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].webm"
Deleting original file /mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].f251.webm (pass -k to keep)
Deleting original file /mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].f248.webm (pass -k to keep)
[Exec] Executing command: ytdlptorclone.sh '/mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].webm'
06/06 07:00:01 [ERROR] Failed to send job to rclone: /mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].webm

please help

**Comment by wy580477** [comment]
Test on my heroku deployment, worked fine.  Have you changed any default options? 

[youtube] t0Q2otsqC4I: Downloading webpage
[youtube] t0Q2otsqC4I: Downloading android player API JSON
[info] t0Q2otsqC4I: Downloading 1 format(s): 248+251
[download] /mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].webm has already been downloaded
[Exec] Executing command: ytdlptorclone.sh '/mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen _ Classic Cartoon Compilation _ WB Kids [t0Q2otsqC4I].webm'
{
	"jobid": 32
}
06/06 15:11:34 [INFO] Successfully send job to rclone: /mnt/data/videos/Tom & Jerry _ Tom & Jerry in Full Screen

**Comment by arjung24** [comment]
i didn't touch any default setting

**Comment by wy580477** [comment]
> i didn't touch any default setting

Did you edit rclone.conf file on windows?

**Comment by arjung24** [comment]
i renamed rclone_options.conf to rclone.conf
then upload there my rclone config text

**Comment by wy580477** [comment]
> i renamed rclone_options.conf to rclone.conf from filebrowser then upload there my rclone config text

rclone_options.conf shoud be kept as it is, it's for rclone options only.

rclone.conf is a seperate file for remotes config.

**Comment by arjung24** [comment]
![Uploading IMG_20220606_131939.jpg…]()

**Comment by wy580477** [comment]
You can't merge rclone_options.conf and rclone.conf into a single file, rclone will fail to start the daemon.

I keep two files seperated for a reason.

**Comment by arjung24** [comment]
thanks brother. it worked using separate files

**Comment by arjung24** [comment]
Another thing brother. does pyload download from different host like rapigator, uptobox etc??

**Comment by wy580477** [comment]
> Another thing brother. does pyload download from different host like rapigator, uptobox etc??

See settings--plugins for supported hosts.

**Comment by arjung24** [comment]
![Uploading IMG_20220606_134043.jpg…]()

**Comment by arjung24** [comment]
Why can't i upload image on GitHub issue. Rapigator works but too slow

**Comment by arjung24** [comment]
Please help brother. Ariang is not getting connected. Loading and loading.
Qbittorrent speed is too much low. Is there any any settings to increase. Cause for same magnet i m getting huge speed using mirrorbot.
Is there any reason for this difference??

**Comment by arjung24** [comment]
Just found qbittorrent speed solution. I changed the Global rate limit to 0. Now it's unlimited.
Only ariang is not connecting now

**Comment by arjung24** [comment]
> > 
> 
> > Please help brother. Ariang is not getting connected. Loading and loading.
> 
> Have you fill in RPC token?

Yes brother

**Comment by wy580477** [comment]
> > > 
> > 
> > 
> > > Please help brother. Ariang is not getting connected. Loading and loading.
> > 
> > 
> > Have you fill in RPC token?
> 
> Yes brother

Make sure PORT is 443 and use HTTPS, the path follow port number shoud be GLOBAL_PORTAL_PATH env without / prefix + /jsonrpc

**Comment by arjung24** [comment]
Aria2 rpc protocol is default http not https

**Comment by wy580477** [comment]
> Should i change it to https??

Change to HTTPS or WSS.

Are you on mobile? All my test are done on PC, always default to https.

**Comment by wy580477** [comment]
> I am on mobile. I changed to https and it got connected. Thanks a lot brother. I love u ❤️❤️❤️

Guess this is a mobile issue. On pc, you can't choose http if port is 443.

**Comment by arjung24** [comment]
There is no option to set proxy on ur olivetin

**Comment by arjung24** [comment]
yt-dlp is not able to download from vimeo
https://vimeo.com/716535616
I can download this video using leech bot yt-dlp though

**Comment by wy580477** [comment]
> yt-dlp is not able to download from vimeo https://vimeo.com/716535616 I can download this video using leech bot yt-dlp though

Tested, works fine.

[vimeo] 716535616: Downloading akfire_interconnect_quic MPD information
[vimeo] 716535616: Downloading akfire_interconnect_quic MPD information
[vimeo] 716535616: Downloading fastly_skyfire MPD information
[vimeo] 716535616: Downloading fastly_skyfire MPD information
[info] 716535616: Downloading 1 format(s): source
[download] Destination: /mnt/data/videos/Heaven Reaches Down To Earth [716535616].mp4
[download] Download completed

**Comment by arjung24** [comment]
> > yt-dlp is not able to download from vimeo https://vimeo.com/716535616 I can download this video using leech bot yt-dlp though
> 
> Tested, works fine.
> 
> [vimeo] 716535616: Downloading akfire_interconnect_quic MPD information [vimeo] 716535616: Downloading akfire_interconnect_quic MPD information [vimeo] 716535616: Downloading fastly_skyfire MPD information [vimeo] 716535616: Downloading fastly_skyfire MPD information [info] 716535616: Downloading 1 format(s): source [download] Destination: /mnt/data/videos/Heaven Reaches Down To Earth [716535616].mp4 [download] Download completed

Now it's also working for me 🤔🤔
