### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by arjung24** [wy580477/Leech-AIO-APP-EX#19]
https://github.com/ripmeapp2/ripme

**Comment by wy580477** [comment]
https://github.com/mikf/gallery-dl

This seems be more suitable，rely on python so I don't need to add more dependencies.

**Comment by arjung24** [comment]
> https://github.com/mikf/gallery-dl
> 
> This seems be more suitable，rely on python so I don't need to add more dependencies.

Maybe this one is only for image downloading not videos playlist. Though i m not all sure.

**Comment by arjung24** [comment]
https://github.com/yaronzz/Tidal-Media-Downloader

**Comment by wy580477** [comment]
gallery-dl is added.

I'm not going to add special tool for individual website.

**Comment by arjung24** [comment]
> gallery-dl is added.
> 
> I'm not going to add special tool for individual website.

Thanks brother.

**Comment by arjung24** [comment]
Just one thing brother how can i update the repo. i deployed previous version

**Comment by wy580477** [comment]
> Just one thing brother how can i update the repo. i deployed previous version

Use github action or deploy from command line by using heroku-cli.  I'm too lasy to write README for that now. 

Github action file is already written, for more information: https://github.com/AkhileshNS/heroku-deploy

**Comment by arjung24** [comment]
> > Just one thing brother how can i update the repo. i deployed previous version
> 
> Use github action or deploy from command line by using heroku-cli. I'm too lazy to write README for that now.
> 
> Github action file is already written, for more information: https://github.com/AkhileshNS/heroku-deploy

Ok Brother. Thanks a lot

**Comment by arjung24** [comment]
Successfully downloaded using gallery-dl ttyd but rclone is not processing for uploading

**Comment by wy580477** [comment]
> Successfully downloaded using gallery-dl ttyd but rclone is not processing for uploading

You need to manually update config files. See release note.

**Comment by arjung24** [comment]
What is this gdlr brother??
Need to edit script.conf??

**Comment by arjung24** [comment]
![IMG_20220609_145606](https://user-images.githubusercontent.com/68998000/172807599-35e0826b-d805-4da1-876c-e7b47197e451.jpg)

Where is this gdlr option here??

**Comment by arjung24** [comment]
![IMG_20220609_150008](https://user-images.githubusercontent.com/68998000/172809054-f88d00a4-e7cc-48e8-838b-6889858cc31d.jpg)
![IMG_20220609_150143](https://user-images.githubusercontent.com/68998000/172809076-0c8fbc25-5783-4816-9b8d-b1a0d01e4a79.jpg)
![IMG_20220609_150248](https://user-images.githubusercontent.com/68998000/172809084-b3c01238-1c2d-438a-87ba-a4198b4df794.jpg)


All are ok??

**Comment by arjung24** [comment]
Space after 57 or 66 number line??

**Comment by arjung24** [comment]
Or maybe i m not getting u

**Comment by wy580477** [comment]
> Or maybe i m not getting u

Just use file from repo to replace your old file.

**Comment by arjung24** [comment]
> ![IMG_20220609_145606](https://user-images.githubusercontent.com/68998000/172807599-35e0826b-d805-4da1-876c-e7b47197e451.jpg)
> 
> Where is this gdlr option here??

Where is this gdlr option??

**Comment by wy580477** [comment]
'gdlr' is an alias for using in ttyd.

For olivetin, clear you have no experience with yaml. So just replace your old file with content/olivetin_config.yaml from repo.

**Comment by arjung24** [comment]
![IMG_20220609_161719](https://user-images.githubusercontent.com/68998000/172824443-2c9dd4f7-e14e-4540-b451-6f47245808ac.jpg)

I succeeded brother. Thanks

**Comment by arjung24** [comment]
![IMG_20220609_161951](https://user-images.githubusercontent.com/68998000/172824989-d4b32be5-5369-45cf-8a49-5e499e432bcf.jpg)

Failed to rclone 😥😥

**Comment by wy580477** [comment]
> Failed to rclone 😥😥

This error most likely is because script fail to get upload mode from script.conf.

Make sure that you have following line in script.conf:

# gallery-dl auto-upload mode. move | copy | disable
gallery-dl-upload-mode=move

**Comment by arjung24** [comment]
Thanks a lot brother. U fulfilled my request. 😍😍
