### ISSUE TITLE
where i can get KEY & GETKEY

### ISSUE THREAD

**Issue by kanjvt** [wy580477/Leech-AIO-APP-EX#20]
i really confused when following here https://github.com/wy580477/PaaS-Related/blob/main/SET_CLOUDFLARE_KV.md 
where i can get KEY & GETKEY? what you meand is Account ID or what? https://telegra.ph/file/ef56c26b2e48a7b067c51.jpg

**Comment by wy580477** [comment]
It's what ever value you want, think it as a password.

**Comment by AmirulAndalib** [comment]
How to get ```CLOUDFLARE_WORKERS_KEY``` @wy580477

**Comment by wy580477** [comment]
> How to get `CLOUDFLARE_WORKERS_KEY` @wy580477

CLOUDFLARE_WORKERS_KEY = KEY & GETKEY value which you set when setting up Cloudflare KV.

**Comment by AmirulAndalib** [comment]
> > How to get `CLOUDFLARE_WORKERS_KEY` @wy580477
> 
> CLOUDFLARE_WORKERS_KEY = KEY & GETKEY value which you set when setting up Cloudflare KV.

Can you elaborate?

**Comment by AmirulAndalib** [comment]
![Screenshot_20220623-122446~2](https://user-images.githubusercontent.com/86344856/175229916-de302c00-20d8-493d-a508-7361ed3b2461.png)

**Comment by wy580477** [comment]
You need keep KEY & GETKEY as the same value, the use this value as CLOUDFLARE_WORKERS_KEY
