### ISSUE TITLE
Vps Support

### ISSUE THREAD

**Issue by rinrinx** [wy580477/Leech-AIO-APP-EX#23]
Can you add support in vps? It would be logical to use it by connecting to a specific port over IP on the Vps server.

**Comment by wy580477** [comment]
> Can you add support in vps? It would be logical to use it by connecting to a specific port over IP on the Vps server.

You can deploy via docker on VPS. https://github.com/wy580477/Leech-AIO-APP-EX/blob/main/docs/README_docker.md

**Comment by rinrinx** [comment]
Is it possible to run this script on cloudflare workers dev?

**Comment by wy580477** [comment]
> Is it possible to run this script on cloudflare workers dev?

No, you can't run binary such as aria2/qbit on workers.
