### ISSUE TITLE
rclone上传问题

### ISSUE THREAD

**Issue by boaom** [wy580477/Leech-AIO-APP-EX#25]
aria2 qb下载完rclone上传不带指定的路径  

## aria2日志

```shell
06/14 05:56:56 [[1;32mNOTICE[0m] Download complete: /mnt/data/aria2_downloads/250/250mb.bin
06/14 05:56:56 [[1;32mINFO[0m] General download task, skipped delete .torrent file.
06/14 05:56:56 [[1;32mINFO[0m] Deleting empty directory ...
06/14 05:56:56 [[1;32mINFO[0m] Start upload files...

-------------------------- [[1;33mTask Infomation[0m] --------------------------
[1;35mTask GID:[0m 90a10c2fba5797fa
[1;35mNumber of Files:[0m 1
[1;35mFirst File Path:[0m /mnt/data/aria2_downloads/250/250mb.bin
[1;35mTask File Name:[0m 250mb.bin
[1;35mTask Path:[0m /mnt/data/aria2_downloads/250/250mb.bin
[1;35mAria2 Download Directory:[0m /mnt/data/aria2_downloads
[1;35mCustom Download Directory:[0m /mnt/data/aria2_downloads/250
[1;35mLocal Path:[0m /mnt/data/aria2_downloads/250/250mb.bin
[1;35mRemote Path:[0m gc:/
[1;35m.aria2 File Path:[0m 
-------------------------- [[1;33mTask Infomation[0m] --------------------------

{
	"jobid": 15
}
06/14 05:56:56 [[1;32mINFO[0m] Successfully send job to rclone: /mnt/data/aria2_downloads/250/250mb.bin -> gd:/
06/14 05:56:56 [[1;32mINFO[0m] Deleting empty directory ...

06/14 05:56:57 [[1;32mNOTICE[0m] Serialized session to '/mnt/data/config/aria2.session' successfully.
```

## qbit日志

```shell
{
	"jobid": 18
}
[INFO] Successfully send job to rclone: /mnt/data/qbit_downloads/Anime/间谍过家家/[Comicat&KissSub][SPY x FAMILY][10][1080P][GB][MP4]/[Comicat&KissSub][SPY x FAMILY][10][1080P][GB][MP4].mp4 -> gd:/
```

![image-20220614143927599](https://cdn.jsdelivr.net/gh/boaom/image@main/img/image-20220614143927599.png)

到网盘只有单文件到挂载根目录

**Comment by wy580477** [comment]
贴一下script.conf里面的上传路径设置。

**Comment by boaom** [comment]
> 贴一下script.conf里面的上传路径设置。

```
# 网盘名称(RCLONE 配置时填写的 name)。默认值auto将从配置文件第一行中提取。

# Rclone remote name. If set to auto, Remote name will be extracted from the first line of rclone config file.

drive-name=auto

# 全局上传目标目录，网盘中的文件夹路径。末尾不要有斜杠。

# global Rclone remote upload path.

drive-dir=/

# Aria2 上传目标目录，网盘中的文件夹路径。末尾不要有斜杠。留空则采用全局上传目标目录。

# Aria2 Rclone remote upload path. If set to empty, global upload path will be used.

aria2-drive-dir=/

# qBittorrent 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。

# qBittorrent Rclone remote upload path. If set to empty, global upload path will be used.

qbit-drive-dir=/

# yt-dlp 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。

# yt-dlp Rclone remote upload path. If set to empty, global upload path will be used.

ytdlp-drive-dir=/

# gallery-dl 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。

# gallery-dl Rclone remote upload path. If set to empty, global upload path will be used.

gdl-drive-dir=/

# pyLoad 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。

# pyLoad Rclone remote upload path. If set to empty, global upload path will be used.

pyload-drive-dir=/
```

**Comment by wy580477** [comment]
> > 贴一下script.conf里面的上传路径设置。
> 
> ```
> # 网盘名称(RCLONE 配置时填写的 name)。默认值auto将从配置文件第一行中提取。
> 
> # Rclone remote name. If set to auto, Remote name will be extracted from the first line of rclone config file.
> 
> drive-name=auto
> 
> # 全局上传目标目录，网盘中的文件夹路径。末尾不要有斜杠。
> 
> # global Rclone remote upload path.
> 
> drive-dir=/
> 
> # Aria2 上传目标目录，网盘中的文件夹路径。末尾不要有斜杠。留空则采用全局上传目标目录。
> 
> # Aria2 Rclone remote upload path. If set to empty, global upload path will be used.
> 
> aria2-drive-dir=/
> 
> # qBittorrent 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。
> 
> # qBittorrent Rclone remote upload path. If set to empty, global upload path will be used.
> 
> qbit-drive-dir=/
> 
> # yt-dlp 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。
> 
> # yt-dlp Rclone remote upload path. If set to empty, global upload path will be used.
> 
> ytdlp-drive-dir=/
> 
> # gallery-dl 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。
> 
> # gallery-dl Rclone remote upload path. If set to empty, global upload path will be used.
> 
> gdl-drive-dir=/
> 
> # pyLoad 上传目标目录，网盘中的文件夹路径)。末尾不要有斜杠。留空则采用全局上传目标目录。
> 
> # pyLoad Rclone remote upload path. If set to empty, global upload path will be used.
> 
> pyload-drive-dir=/
> ```

你全设置成根目录当然上传到根目录了，我觉得我写的说明不算难懂吧。

**Comment by wy580477** [comment]
额，想要保留目录结构啊，等过几天有时间看看搞一下。

**Comment by boaom** [comment]
> 额，想要保留目录结构啊，等过几天有时间看看搞一下。

thanks

**Comment by wy580477** [comment]
> > 额，想要保留目录结构啊，等过几天有时间看看搞一下。
> 
> thanks

已经搞好了。
