### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by arjung24** [wy580477/Leech-AIO-APP-EX#26]
Why getting this security error brother??
Can u check please??
It can be chrome browser issue.
Cause brave browser not showing this error.

**Comment by arjung24** [comment]
![IMG_20220615_210139](https://user-images.githubusercontent.com/68998000/173860499-3611d5eb-669a-49d1-a816-e7b77735b887.jpg)

**Comment by wy580477** [comment]
My heroku deployment has no problem on Chrome android.

Perhaps previous owner of this heroku domain got it blacklisted.

You can try to deploy to a different domain.

**Comment by arjung24** [comment]
Ok brother. Thanks

**Comment by arjung24** [comment]
My heroku account again got banned 😭😭

**Comment by wy580477** [comment]
> My heroku account again got banned 😭😭

Can you share with me how did you get banned? Which downloader did you use?

**Comment by arjung24** [comment]
Idk how. I was using gallery-dl ( trying to download Instagram user profile ). Suddenly my website was offline. Checked that i couldn't sign in to heroku account then.

**Comment by arjung24** [comment]
If possible drop gallery-dl and add ripme.

**Comment by arjung24** [comment]
Again my 2 heroku account got banned 😭😭

**Comment by arjung24** [comment]
Again deployed and again ban 😭😭😭😭😭

**Comment by arjung24** [comment]
Should i use different cloudflare worker for every deploy??
