### ISSUE TITLE
Some help needed

### ISSUE THREAD

**Issue by AmirulAndalib** [wy580477/Leech-AIO-APP-EX#27]
Hi there

First of all thanks to your wonderful repo

I was trying to deploy on github actions using localtunnel and docker But I am facing some problems can you help me Deploy it to github actions

Thank you

Logs here 

https://github.com/AmirulAndalib/botflow/runs/6913083114?check_suite_focus=true

**Comment by wy580477** [comment]
Did a quick look.

I think you should git clone Colab branch. The main branch is for alpine container,  busybox unzip command doesn't work on ubuntu. 

Colab branch is for ubuntu. After git clone, copy everything under content folder to /workdir, then run following command:

echo GLOBAL_LANGUAGE=en >/etc/env
# Change to Enable if you want to install pyLoad
echo PYLOAD_INSTALL=Disable >>/etc/env
echo PYLOAD_INSTALL=Disable >>/etc/env
sed -i $'s/\r$//' /workdir/install.sh
bash /workdir/install.sh

**Comment by AmirulAndalib** [comment]
Ok so I apparently tried the docker branch but I am facing an error

```  allinone    | ./run: source: line 7: can't open '/mnt/data/config/rclone_options.conf': No such file or directory ```

![Screenshot_20220616-155530](https://user-images.githubusercontent.com/86344856/174045481-19c3bb9d-4b7f-4105-9ce2-568805394e1c.png)


Repo I used (personal)
https://github.com/AmirulAndalib/Leech-AIO-APP-EX/blob/docker/docker-compose.yml

**Comment by wy580477** [comment]
> Ok so I apparently tried the docker branch but I am facing an error
> 
This a minor error which shouldn't cause troubles.

**Comment by AmirulAndalib** [comment]
Localtunnel is routing port 8080 currently

**Comment by AmirulAndalib** [comment]
> > Even after setting port 443 in secrets it's showing error
> > `Client sent an HTTP request to an HTTPS server.`
> 
> You should set CADDY_DOMAIN to 'http://localhost', CADDY_WEB_PORT to 8080. Then let your tunnel route traffic to 8080.

Doesnt still work now shows white blank page

https://github.com/AmirulAndalib/botflow/runs/6950031060?check_suite_focus=true

https://couchpotato69.loca.lt

**Comment by wy580477** [comment]
> Doesnt still work now shows white blank page

It’s working，you forgot to add portal path.

**Comment by AmirulAndalib** [comment]
> > Doesnt still work now shows white blank page
> 
> It’s working，you forgot to add portal path.

![Screenshot_20220619-122800~2](https://user-images.githubusercontent.com/86344856/174468794-a0beb540-347c-4e31-972d-f655c55bffd7.png)
![Screenshot_20220619-122642](https://user-images.githubusercontent.com/86344856/174468795-441506d2-bcc1-44e2-be10-089494838c3c.png)

**Comment by AmirulAndalib** [comment]
No reply

**Comment by AmirulAndalib** [comment]
@wy580477 my heroku settings being deleted after reboot

**Comment by wy580477** [comment]
> @wy580477 my heroku settings being deleted after reboot

There was a Cloudflare outrage. Currently if app fails to get backup data from CF, it will overwrite KV data with default config.

This certainly needs improvement. I haven't thought out a way yet.
