### ISSUE TITLE
.torrent file

### ISSUE THREAD

**Issue by pctechkid** [wy580477/Leech-AIO-APP-EX#28]
On aria2, after uploading/direct linking (from a torrent website ) a .torrent to the ariaNg is successful, the problem is when the rclone auto-upload is triggered, the .torrent file itself is uploaded into the google drive. How to disable auto uploading or excluding .torrent files to be uploaded by rclone?

**Comment by wy580477** [comment]
Well, this is  a bit harder to deal with than what I expected.

I tried to add filter option to rclone daemon, this didn't work. 

This likely will require a new option in script.conf.

**Comment by wy580477** [comment]
Well. This turned out a bit harder than what I expected.

I added exclude filter to rclone daemon, it didn't work. 

I will leave this as it is for now. I will revisit this issue when I have more time.

**Comment by pctechkid** [comment]
> Well. This turned out a bit harder than what I expected.
> 
> I added exclude filter to rclone daemon, it didn't work.
> 
> I will leave this as it is for now. I will revisit this issue when I have more time.

Did this too and was surprised the exclude filter didn't worked out.

I solved this issue before but I dont know how to apply it on rclone rc POST. The code goes like this:

```rclone delete -v "drivename:" --include "*.torrent" --drive-use-trash=false```

The idea is that it just lets rclone upload the .torrent file, and right after uploading it, it also automatically just deletes the .torrent file too by itself. Maybe you can implement that using rclone rc command in the upload.sh.

**Comment by wy580477** [comment]
> Did this too and was surprised the exclude filter didn't worked out.
> 
> I solved this issue before but I dont know how to apply it on rclone rc POST. The code goes like this:
> 
> `rclone delete -v "drivename:" --include "*.torrent" --drive-use-trash=false`
> 
> The idea is that it just lets rclone upload the .torrent file, and right after uploading it, it also automatically just deletes the .torrent file too (on the google drive) by itself. Maybe you can implement that using rclone rc command in the upload.sh.

I still haven't find a way to apply filter to api call.

Here is a work around.

```
if  [[ "${TASK_FILE_NAME}" = *".torrent" ]]; then
    curl -u ${GLOBAL_USER}:${GLOBAL_PASSWORD} -H "Content-Type: application/json" -f -X POST -d '{"fs":"'"${REMOTE_PATH}"'","remote":"'"${TASK_FILE_NAME}"'"}' 'localhost:61802/operations/deletefile'
fi
```

**Comment by wy580477** [comment]
[566632b0093c3c44a11514b589c5c3cf8491f26aa64b9b9e1bd0fe9a76f9f4b7](https://github.com/wy580477/Leech-AIO-APP-EX/commit/7c22a72438dac4546445244bbc1dfebb688fee97#diff-566632b0093c3c44a11514b589c5c3cf8491f26aa64b9b9e1bd0fe9a76f9f4b7)

Aria2 auto-upload Include/Exclude filter base on file extensions added.

**Comment by pctechkid** [comment]
Thank you. This did the trick.

However, Heroku now starts banning your repo (fresh deploy, 1 single torrent file 200mb for testing), they seem to have detected your code already. I got mine banned just now.

**Comment by wy580477** [comment]
> Thank you. This did the trick.
> 
> However, Heroku now starts banning your repo (fresh deploy, 1 single torrent file 200mb for testing), they seem to have detected your code already. I got mine banned just now.

Did you deploy via web url? My heroku app is deployed via Heroku cli, it's still working fine.

Please help me test by using Heroku cli or github action to deploy.

How to deploy via Heroku cli:
1. Install git and Heroku cli
2. git clone repo to local device.
3. Change path to git folder on command line.
4. Run "heroku login" to login into Heroku.
5. Run "heroku git:remote -a \<your app name\>"
6. Run "git push heroku --force"

How to deploy via github action:
1. pull my newest commit to your fork.
3. Create a new app in Heroku dashboard, set up config vars according to app.json in repo.
7. Set up action secrets in repo settings. You can get Heroku api key from Heroku account setting page in Heroku dashboard.
![image](https://user-images.githubusercontent.com/98247050/174502593-4dde5b7b-1098-4e6b-8de6-2f385481fd13.png)
8. Create a new release with tag like v0.0.1, then action will be triggered.

**Comment by pctechkid** [comment]
> > Thank you. This did the trick.
> > However, Heroku now starts banning your repo (fresh deploy, 1 single torrent file 200mb for testing), they seem to have detected your code already. I got mine banned just now.
> 
> Did you deploy via web url? My heroku app is deployed via Heroku cli, it's still working fine.
> 
> Please help me test by using Heroku cli or github action to deploy.
> 
> How to deploy via Heroku cli:
> 
> 1. Install git and Heroku cli
> 2. git clone repo to local device.
> 3. Change path to git folder on command line.
> 4. Run "heroku login" to login into Heroku.
> 5. Run "heroku create <your new app name> --manifest --region eu". You can choose us or eu for region.
> 6. Run "heroku config:set KEY=VALUE" to set up config vars according to app.json in repo.
> 7. Run "heroku git:remote -a <your new app name>"
> 8. Run "git push heroku --force"
> 
> How to deploy via github action:
> 
> 1. pull my newest commit to your fork.
> 2. Set up action secrets in repo settings. You can get Heroku api key from Heroku account setting page in Heroku dashboard.
>    ![image](https://user-images.githubusercontent.com/98247050/174502593-4dde5b7b-1098-4e6b-8de6-2f385481fd13.png)
> 3. Create a new release with tag like v0.0.1_deploy, then action will be triggered.
> 4. Set up config vars in Heroku dashboard according to app.json in repo.

Yes sir, I would help you test with that. I'll do these right after I'm off with my vacation and will let you know afterwards.

Thanks for your hard work!
