### ISSUE TITLE
Uodate not showing on heroku

### ISSUE THREAD

**Issue by nimma0001** [wy580477/Leech-AIO-APP-EX#30]
After  deploy update not showing I have pulled the latest commit and deployed again

**Comment by nimma0001** [comment]
Add some way to delete kV worker  data

**Comment by nimma0001** [comment]
I used manual way

**Comment by nimma0001** [comment]
Close this after u have seen this issue

**Comment by wy580477** [comment]
> After deploy update not showing I have pulled the latest commit and deployed again

You need to manually update script.conf file and olivetin/config.yaml file under config folder.

> Add some way to delete kV worker data

![image](https://user-images.githubusercontent.com/98247050/174501938-5bc6a889-4a6c-4290-af45-76e55c30af09.png)

You can delete KV data in Cloudflare dashboard.

**Comment by nimma0001** [comment]
Save rclone config data in different backup please

**Comment by nimma0001** [comment]
Thanks for quick reply keep the good work.

Close this after u check it
