### ISSUE TITLE
jdownloader 

### ISSUE THREAD

**Issue by nimma0001** [wy580477/Leech-AIO-APP-EX#33]
Could u add jdownloader in this.
Jdownloader have many plugin which pyload doesn't have .
If possible

**Comment by AmirulAndalib** [comment]
Yes +1

**Comment by wy580477** [comment]
1. I'm not a fan of jdownloader's semi-selfhost mode.
2. I rarely use One-click hosting sites. So I'm not planing to spending more time on it.
    Pull request is welcome.
