### ISSUE TITLE
Aria2 rpc

### ISSUE THREAD

**Issue by nimma0001** [wy580477/Leech-AIO-APP-EX#34]
Cant add to prowlaar

**Comment by wy580477** [comment]
Try xml rpc path in README.

**Comment by nimma0001** [comment]
Not working i added 
Host : appname.herokuapp.com
Xmlrpc : /mypath/rpc
Port : 443 tried 80 tried
Token = password

**Comment by nimma0001** [comment]
Port : 61800

**Comment by nimma0001** [comment]
Any way to dm u it not working

**Comment by nimma0001** [comment]
I am using heroku deployment

Can u dm me on telegram @r5pro so i can share u the aio

**Comment by nimma0001** [comment]
I am really sorry.
I realized that i was using ip6 server
