### ISSUE TITLE
App requests and improvements

### ISSUE THREAD

**Issue by AmirulAndalib** [wy580477/Leech-AIO-APP-EX#35]
Hi can you please add the following features:

1) sync jellyfin with Rclone mount and config backup

2) using metube and Ubuntu docker image

3) jackett

I was currently using railway.app for hosting and it does support rclone mount but strict anyway I bypassed it hope you can make a separate branch and make some improvements 

Please try to add them thank you very much

**Comment by wy580477** [comment]
This app is for Downloaders to Rclone auto-upload. It's not intend to be an OS with every kinds of apps.

1. Jellyfin needs a database and generates lots of file for metadata, so it's not suitable for PaaS platforms' ephemeral file system.
2. I dropped metube from Heroku deployment for generic alpine as base image,  so Heroku can't ban repos based on image layer.
3. I don't have time to get into jackett/plowarr for now. Perhaps I will write a standlone jackett/plowarr app for PaaS platforms in the future.

**Comment by wy580477** [comment]
Got prowlarr up and running on a PaaS service. Kinda of disappointment.....

Some of most popular trackers use ddos protection, so you will some of kind of proxy for indexer to work.

Not sure if it is worth the effort,  it seems to be more suitable on home server.  
Indexers barely take up any bandwidth, so even on crappy ISP it would work well.

**Comment by AmirulAndalib** [comment]
Whats prowlarr only jackett is real
