### ISSUE TITLE
ytdlp

### ISSUE THREAD

**Issue by arjung24** [wy580477/Leech-AIO-APP-EX#36]
![IMG_20220629_131202](https://user-images.githubusercontent.com/68998000/176374902-8e214289-e77b-4b49-8d46-cf30267deb4d.jpg)
![IMG_20220629_131305](https://user-images.githubusercontent.com/68998000/176374914-3eaf3fcc-9dcc-4417-a482-a4da24f96823.jpg)

Please help.

**Comment by arjung24** [comment]
Ohh god banned again. Brother please do something. Heroku banning all the accounts deploying this repo. Please do something 🙏🙏🙏

**Comment by wy580477** [comment]
1. Give me the video link so I can test it.

2. It's not helping that you are screaming at me without any info. I ran over 100GB downloads via aria2 without issue yesterday.
    You need to give info such as which downloader did you use and you got banned during downloading or uploading.
    You can help me by testing deploy via heroku cli or github action:
    https://github.com/wy580477/Leech-AIO-APP-EX/issues/28#issuecomment-1159822885

**Comment by arjung24** [comment]
https://www.ertflix.gr/en/series/ser.176310-agape-paranome

I will definitely try github action

**Comment by wy580477** [comment]
![image](https://user-images.githubusercontent.com/98247050/177024682-698ca462-4d67-4c10-af7d-db60a0d22457.png)

I can't reproduce your problem

**Comment by wy580477** [comment]
![image](https://user-images.githubusercontent.com/98247050/177024721-d9fc7596-55d3-4d6e-a426-0cfbedd12295.png)

I can't reproduce your problem.

**Comment by arjung24** [comment]
Olivetin??
Maybe my ytdlp was not updated

**Comment by wy580477** [comment]
> Olivetin?? Maybe my ytdlp was not updated

Olivetin. yt-dlp is updated each time dyno restarts.

**Comment by arjung24** [comment]
Problem is i m talking about docker deployment now. As i can't use heroku for now. I will try later with GitHub action

**Comment by arjung24** [comment]
Is it possible to update docker deployment without reinstall everything again

**Comment by arjung24** [comment]
![IMG_20220703_104123](https://user-images.githubusercontent.com/68998000/177024935-2c87068f-8f80-439d-b375-365540c8389d.jpg)

**Comment by wy580477** [comment]
> Is it possible to update docker deployment without reinstall everything again

Of couse you can.  If you mounted docker volume on host, you won't lost anything.

![image](https://user-images.githubusercontent.com/98247050/177025056-43cd34a1-99bb-4b01-9471-b1890c1e6007.png)

**Comment by arjung24** [comment]
What i did to deploy docker deployment:
1. I uploaded docker-compose.yaml on main branch
2. I git clone main branch on vps
3. I set .env inside docker-compose.yaml file
4. Then i ran this cmd     "docker-compose -f docker-compose_en.yml up -d"
Was it okay? Can i update now following your above command??

**Comment by wy580477** [comment]
> What i did to deploy docker deployment:
> 
> 1. I uploaded docker-compose.yaml on main branch
> 2. I git clone main branch on vps
> 3. I set .env inside docker-compose.yaml file
> 4. Then i ran this cmd     "docker-compose -f docker-compose_en.yml up -d"
>    Was it okay? Can i update now following your above command??

Run following command:
docker-compose -f docker-compose_en.yml down
docker-compose -f docker-compose_en.yml pull
docker-compose -f docker-compose_en.yml up -d

**Comment by arjung24** [comment]
> 

Done.
Will metube now work with latest yt-dlp??

**Comment by arjung24** [comment]
> > What i did to deploy docker deployment:
> > 
> > 1. I uploaded docker-compose.yaml on main branch
> > 2. I git clone main branch on vps
> > 3. I set .env inside docker-compose.yaml file
> > 4. Then i ran this cmd     "docker-compose -f docker-compose_en.yml up -d"
> >    Was it okay? Can i update now following your above command??
> 
> Run following command: docker-compose -f docker-compose_en.yml down docker-compose -f docker-compose_en.yml pull docker-compose -f docker-compose_en.yml up -d

Metube is working now perfectly fine. 

Please check the below issue
https://github.com/wy580477/Leech-AIO-APP-EX/issues/37#issuecomment-1173002560

Another issue
    docker exec -it allinone sh
    # enter container shell
    sv stop filebrowser
    # stop filebrowser service
    filebrowser -d /mnt/config/filebrowser.db users add username password --perm.admin
    # add new account with admin privileges
    sv start filebrowser
    # start filebrowser service
I ran above cmd but it's not working.

![IMG_20220703_111213](https://user-images.githubusercontent.com/68998000/177025847-1ad902c1-2c53-4008-85b9-ecb44f1fd13c.jpg)

**Comment by wy580477** [comment]
> Another issue docker exec -it allinone sh # enter container shell sv stop filebrowser # stop filebrowser service filebrowser -d /mnt/config/filebrowser.db users add username password --perm.admin # add new account with admin privileges sv start filebrowser # start filebrowser service I ran above cmd but it's not working.

Path shoud be '/mnt/data/config/filebrowser.db' . I forgot to correct README.

**Comment by arjung24** [comment]
> > Another issue docker exec -it allinone sh # enter container shell sv stop filebrowser # stop filebrowser service filebrowser -d /mnt/config/filebrowser.db users add username password --perm.admin # add new account with admin privileges sv start filebrowser # start filebrowser service I ran above cmd but it's not working.
> 
> Path shoud be '/mnt/data/config/filebrowser.db' . I forgot to correct README.

Ohh i see. 😊😊

**Comment by arjung24** [comment]
> > Another issue docker exec -it allinone sh # enter container shell sv stop filebrowser # stop filebrowser service filebrowser -d /mnt/config/filebrowser.db users add username password --perm.admin # add new account with admin privileges sv start filebrowser # start filebrowser service I ran above cmd but it's not working.
> 
> Path shoud be '/mnt/data/config/filebrowser.db' . I forgot to correct README.

![IMG_20220703_120710](https://user-images.githubusercontent.com/68998000/177027202-6f2a110c-9a0a-4394-b8a6-a42c1010ce5c.jpg)

**Comment by arjung24** [comment]
![IMG_20220703_123143](https://user-images.githubusercontent.com/68998000/177028025-e94fe38d-5bf2-4816-97c7-9bc1cf631d5b.jpg)

**Comment by wy580477** [comment]
> 

You have to whitelist commands in filebrowser user setting.

**Comment by arjung24** [comment]
![Uploading IMG_20220703_124214.jpg…]()
My settings are this. Do i need to do anything else to whitelist the command??

**Comment by arjung24** [comment]
![IMG_20220703_124214](https://user-images.githubusercontent.com/68998000/177028683-ecfab829-e51b-417d-b20d-6c1f74b09adb.jpg)

My settings are this. Do i need to do anything else to whitelist the command??

**Comment by wy580477** [comment]
Come on. Add command to the form at the bottom.

Why am I teaching you how to use filebrowser here? I shoud have better thing to do in my life.....

**Comment by arjung24** [comment]
> Come on. Add command to the form at the bottom.
> 
> Why am I teaching you how to use filebrowser here? I shoud have better thing to do in my life.....

Sorry brother. Don't be angry with me.

**Comment by arjung24** [comment]
> Come on. Add command to the form at the bottom.
> 
> Why am I teaching you how to use filebrowser here? I shoud have better thing to do in my life.....

I added the command in bottom

gdlr -u username -p password https://instagram.com/bhabna_ashna

But not working

**Comment by wy580477** [comment]
> > Come on. Add command to the form at the bottom.
> > Why am I teaching you how to use filebrowser here? I shoud have better thing to do in my life.....
> 
> I added the command in bottom
> 
> gdlr -u username -p password https://instagram.com/bhabna_ashna
> 
> But not working

![image](https://user-images.githubusercontent.com/98247050/177036658-1edfccf2-05e5-4186-b150-ab9e0c74cc8d.png)

I don't have instagram account. So did a test with twitter link, works fine.

**Comment by arjung24** [comment]
> > > Come on. Add command to the form at the bottom.
> > > Why am I teaching you how to use filebrowser here? I shoud have better thing to do in my life.....
> > 
> > 
> > I added the command in bottom
> > gdlr -u username -p password https://instagram.com/bhabna_ashna
> > But not working
> 
> ![image](https://user-images.githubusercontent.com/98247050/177036658-1edfccf2-05e5-4186-b150-ab9e0c74cc8d.png)
> 
> I don't have instagram account. So did a test with twitter link, works fine.

can i run rclone move command in filebrowser shell??
To move files from gallery_dl_downloads to google drive??

**Comment by wy580477** [comment]
> can i run rclone move command in filebrowser shell?? To move files from gallery_dl_downloads to google drive??

You can run any command as long as it's whitelisted.

**Comment by arjung24** [comment]
> > > Come on. Add command to the form at the bottom.
> > > Why am I teaching you how to use filebrowser here? I shoud have better thing to do in my life.....
> > 
> > 
> > I added the command in bottom
> > gdlr -u username -p password https://instagram.com/bhabna_ashna
> > But not working
> 
> ![image](https://user-images.githubusercontent.com/98247050/177036658-1edfccf2-05e5-4186-b150-ab9e0c74cc8d.png)
> 
> I don't have instagram account. So did a test with twitter link, works fine.

I got succeeded also brother. But it's downloading all the files not moving to drive.
But when i m downloading one file using gdlr, it moves the file to drive
Strange 🤔🤔

**Comment by arjung24** [comment]
> > can i run rclone move command in filebrowser shell?? To move files from gallery_dl_downloads to google drive??
> 
> You can run any command as long as it's whitelisted.

Don't be angry with me brother. Forgive me if asking wrong.
Can u help me telling the command to move files from gallery_dl_downloads to my google drive via rclone 🙏🙏

**Comment by arjung24** [comment]
I whitelisted rclone command but it's showing 
![IMG_20220703_172428](https://user-images.githubusercontent.com/68998000/177037312-742f9007-4e9b-4952-9f07-86d8c8af5977.jpg)

**Comment by wy580477** [comment]
> Don't be angry with me brother. Forgive me if asking wrong. Can u help me telling the command to move files from gallery_dl_downloads to my google drive via rclone 🙏🙏

There is an easy way.  Add following to rclone.conf file:

[local]
type = alias
remote = /mnt/data

Then you can drag local folder/file to Rclone remote in Rclone WebUI.

**Comment by wy580477** [comment]
> I whitelisted rclone command but it's showing ![IMG_20220703_172428](https://user-images.githubusercontent.com/68998000/177037312-742f9007-4e9b-4952-9f07-86d8c8af5977.jpg)

I can't reproduce your problem

![image](https://user-images.githubusercontent.com/98247050/177037411-ba06cfd6-251e-4ae4-bea3-18e4c6c4e36d.png)

**Comment by arjung24** [comment]
> 

I added local to rclone.conf

![IMG_20220703_174211](https://user-images.githubusercontent.com/68998000/177038015-192792b9-d62f-44ce-8cc7-ebedb3e2d593.jpg)
![IMG_20220703_174232](https://user-images.githubusercontent.com/68998000/177038016-fd145f14-9359-4410-924f-db66b0405d71.jpg)

**Comment by wy580477** [comment]
> I added local to rclone.conf and also i whitelisted the following rclone command

Something went wrong when you add rclone command to whitelist.

Just use Rclone WebUI, it's way easier.

**Comment by arjung24** [comment]
> > I added local to rclone.conf and also i whitelisted the following rclone command
> 
> Something went wrong when you add rclone command to whitelist.
> 
> Just use Rclone WebUI, it's way easier.

Did u mean rclone serve??

**Comment by arjung24** [comment]
![IMG_20220703_174804](https://user-images.githubusercontent.com/68998000/177038183-56da3c03-8f62-4ff7-88c1-d74db160b4c9.jpg)
This one??

**Comment by wy580477** [comment]
> Did u mean rclone serve??

![image](https://user-images.githubusercontent.com/98247050/177038181-b60ee8d2-388b-4b81-9d25-ea006b1a6acd.png)

You are driving me mad....

**Comment by arjung24** [comment]
> > Did u mean rclone serve??
> 
> ![image](https://user-images.githubusercontent.com/98247050/177038181-b60ee8d2-388b-4b81-9d25-ea006b1a6acd.png)
> 
> You are driving me mad....

Actually I can't find any options here to move from local to drive
![IMG_20220703_175007](https://user-images.githubusercontent.com/68998000/177038257-575ba678-f455-4864-9d21-7f40ff788292.jpg)

**Comment by arjung24** [comment]
> > Did u mean rclone serve??
> 
> ![image](https://user-images.githubusercontent.com/98247050/177038181-b60ee8d2-388b-4b81-9d25-ea006b1a6acd.png)
> 
> You are driving me mad....

Don't scare me brother. I am your little brother 😊😊

**Comment by wy580477** [comment]
![image](https://user-images.githubusercontent.com/98247050/177038600-68148968-9bca-4571-b306-78851c1b96d4.png)

My last reply. I'm not your free tech teacher to guild you step by step. Learn to read offical docs.

**Comment by arjung24** [comment]
> ![image](https://user-images.githubusercontent.com/98247050/177038600-68148968-9bca-4571-b306-78851c1b96d4.png)
> 
> My last reply. I'm not your free tech teacher to guild you step by step.

Thanks a lot brother. I won't spare u my brother. If needed i will make u my premium teacher 😍😍
