### ISSUE TITLE
Olivetin Missing

### ISSUE THREAD

**Issue by arjung24** [wy580477/Leech-AIO-APP-EX#37]
Please add olivetin in docker deployment

**Comment by wy580477** [comment]
In docker deployment, I don't enable perm.admin for default user in filebrowser and leave out olivetin & ttyd for security reason.

I think it's not a good idea which potential attacker can execute any command on your own hardware/VPS.

**Comment by arjung24** [comment]
Everything is fine in docker. I was asking for olivetin to run gallery-dl. That's all.

**Comment by arjung24** [comment]
Don't mind brother. I don't get that filebrowser shell. Where is it??

**Comment by wy580477** [comment]
> Don't mind brother. I don't get that filebrowser shell. Where is it??

![image](https://user-images.githubusercontent.com/98247050/177022865-02a0f2f3-7f6b-41b5-a190-687ddc11a511.png)
Click here.

**Comment by arjung24** [comment]
docker exec allinone gdlr -u username -p password https://instagram.com/bhabna_ashna

I ran above cmd in host terminal. It downloaded all the files. But rclone upload is not working. Can u please try it in host terminal to test.

**Comment by arjung24** [comment]
![IMG_20220703_091527](https://user-images.githubusercontent.com/68998000/177023067-9ea6d319-a743-4f48-bad5-8de4745a159f.jpg)

Nothing is happening brother

**Comment by wy580477** [comment]
> I ran above cmd in host terminal. It downloaded all the files. But rclone upload is not working. Can u please try it in host terminal to test.

Currently I don't have access to a linux host. I will test later.

**Comment by arjung24** [comment]
> > I ran above cmd in host terminal. It downloaded all the files. But rclone upload is not working. Can u please try it in host terminal to test.
> 
> Currently I don't have access to a linux host. I will test later.

Ok brother

**Comment by arjung24** [comment]
> ![IMG_20220703_091527](https://user-images.githubusercontent.com/68998000/177023067-9ea6d319-a743-4f48-bad5-8de4745a159f.jpg)
> 
> Nothing is happening brother

Is this because I don't have admin permission of filebrowser??

**Comment by arjung24** [comment]
> > I ran above cmd in host terminal. It downloaded all the files. But rclone upload is not working. Can u please try it in host terminal to test.
> 
> Currently I don't have access to a linux host. I will test later.

U can use my credentials if u want. I can mail u

**Comment by arjung24** [comment]
Also is it possible to update the docker deployment without reinstall everything again??
