### ISSUE TITLE
KV backup field？

### ISSUE THREAD

**Issue by 9568568** [wy580477/Leech-AIO-APP-EX#38]
Where can I modify the KV backup file field name?

**Comment by wy580477** [comment]
![image](https://user-images.githubusercontent.com/98247050/177217885-48138c55-ef37-4d0a-88df-f8823e11081d.png)

If you means KV key name here,  it's hard coded.  

You needs to modify /content/entrypoint.sh and /content/service/backup_files/run.

**Comment by 9568568** [comment]
thx,how to modify?

**Comment by wy580477** [comment]
> thx,how to modify?

In entrypoint.sh:
BACKUP=$(curl --retry 4 https://${CLOUDFLARE_WORKERS_HOST}/backup?key=${CLOUDFLARE_WORKERS_KEY} | jq .value)

In /content/service/backup_files/run:
echo \{\"_id\":\"backup\",\"value\":\"${VALUE}\"\} >./body

Chang "backup" to whichever string you want.

**Comment by 9568568** [comment]
it work.thx!

**Comment by wy580477** [comment]
> it work.thx!

Be aware, free KV service has 1000 writes per day limit. This app will has around 150 writes per day.

If you use single Cloudflare accout for multiple deployment, watch out for writes limit.

**Comment by 9568568** [comment]
Ok,thank you very much!
