### ISSUE TITLE
期望

### ISSUE THREAD

**Issue by bestruirui** [wy580477/Leech-AIO-APP-EX#39]
未来会支持部署在vps上吗？

**Comment by wy580477** [comment]
https://github.com/wy580477/Leech-AIO-APP-EX/blob/main/docs/README_docker_chs.md

**Comment by bestruirui** [comment]
linux环境下的

**Comment by wy580477** [comment]
> linux环境下的

？？？Docker就是运行在linux内核上的。

至于脚本式直接安装到系统里，我没时间精力适配各种操作系统环境，不在计划中。
