### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by 54nzg** [wy580477/Leech-AIO-APP-EX#40]
![image](https://user-images.githubusercontent.com/82253076/177561868-2d9ae947-237a-4eaa-ba8a-f0fba1badb2e.png)

**Comment by 54nzg** [comment]
除这两者外，其他应用均正常

**Comment by wy580477** [comment]
qbit无法登陆的情况之前有人遇到过，我这里一直无法复现。

可以尝试下面的解决办法：


1. 通过filebrowser删除 config/qBittorrent/config/qBittorrent.conf 文件。
2. 在宿主机终端执行 docker exec allinone sv restart qBittorrent

RcloneWeb无法登录的话，请清空浏览器缓存，再尝试，注意检查登录框里面地址的协议和端口是否正确。

**Comment by 54nzg** [comment]
> 

已解决，我使用nginx反代后，一切恢复正常。具体原因未知。

**Comment by wy580477** [comment]
> > 
> 
> 已解决，我使用nginx反代后，一切恢复正常。具体原因未知。

反代以后应该是换了端口，不会用到原来的浏览器缓存，RcloneWeb就正常了。

qBit的问题比较奇怪，我觉得可能是程序本身的偶发bug。

**Comment by wy580477** [comment]
> 已解决，我使用nginx反代后，一切恢复正常。具体原因未知。

隔着这么长时间，我大概发现了原因，qbit 默认会验证 header Host 字段，需要反代过程中修改 Host 字段。

https://github.com/wy580477/Leech-AIO-APP-EX/commit/9729effe49647560b07cc7b34e75348f5d7540f6

至于为啥部分网络环境下才会遇到这个问题，我也不明白。
