### ISSUE TITLE
MountPoint Error

### ISSUE THREAD

**Issue by junkvaibhavyadav** [wy580477/Leech-AIO-APP-EX#42]
I first created a folder named “onedrive” using a file browser
Then tried mounting onedrive and put path “/mnt/data/onedrive” in Mountpoint field but it shows error code 500

**Comment by wy580477** [comment]
If you are trying to mount Rclone remote in Heroku deployment, it's not going to work.
Heroku's linux kernel lacks fuse mod which is needed for rclone mount.

**Comment by junkvaibhavyadav** [comment]
Oh okayy I got it , thanks :-)
