### ISSUE TITLE
qBittorrent和VueTorrent默认账户密码错误

### ISSUE THREAD

**Issue by crosspacific** [wy580477/Leech-AIO-APP-EX#45]
Heroku搭建的AIO，其他功能都正常，但是qBittorrent和VueTorrent使用用户admin和密码adminadmin出错，提示无效的用户名或密码。

**Comment by wy580477** [comment]
qbit无法登陆的情况之前有人遇到过，我这里一直无法复现。

可以尝试下面的解决办法：

1. 通过filebrowser删除 config/qBittorrent/config/qBittorrent.conf 文件。
2. 在ttyd中执行 sv restart 1

**Comment by crosspacific** [comment]
执行以后可以了

**Comment by wy580477** [comment]
> 你好。我用Heroku搭建的，虽然绑定了KV和workers，但每一次休眠重启以后，配置都丢失，还是要上传rclone.conf以及修改script.conf。请问这是正常的吗？谢谢。

不正常。重启后应该从KV取回配置文件的。

看一下log/backup_files/current文件的内容，里面有没有出错信息。

**Comment by crosspacific** [comment]
> > 你好。我用Heroku搭建的，虽然绑定了KV和workers，但每一次休眠重启以后，配置都丢失，还是要上传rclone.conf以及修改script.conf。请问这是正常的吗？谢谢。
> 
> 不正常。重启后应该从KV取回配置文件的。
> 
> 看一下log/backup_files/current文件的内容，里面有没有出错信息。

没有。每次重启之后，里面是空白的文件。

**Comment by wy580477** [comment]
> > > 你好。我用Heroku搭建的，虽然绑定了KV和workers，但每一次休眠重启以后，配置都丢失，还是要上传rclone.conf以及修改script.conf。请问这是正常的吗？谢谢。
> > 
> > 
> > 不正常。重启后应该从KV取回配置文件的。
> > 看一下log/backup_files/current文件的内容，里面有没有出错信息。
> 
> 没有。每次重启之后，里面是空白的文件。

重启等10分钟以后看一下。
