### ISSUE TITLE
YouTube drive

### ISSUE THREAD

**Issue by Un-0wn** [wy580477/Leech-AIO-APP-EX#47]
can you implement youtube drive in it
Link - https://github.com/lewangdev/youtube-drive

**Comment by wy580477** [comment]
`it produces a video of size 127.5MB, and the original size is 476KB.`

I don't think it's suitable for file-storage now.

**Comment by arjung24** [comment]
@wy580477 hey brother. What about this??
https://github.com/filecxx/FileCentipede

**Comment by arjung24** [comment]
Also try this if possible
https://github.com/ajnart/homarr

**Comment by arjung24** [comment]
Also if possible
https://github.com/autobrr/autobrr
