### ISSUE TITLE
how to use Xray Vmess proxy?

### ISSUE THREAD

**Issue by TheCez04** [wy580477/Leech-AIO-APP-EX#48]
Can you please tell me how to setup and use this vmess proxy on shadowsocks android and which client to use for linux and its settings?

**Comment by wy580477** [comment]
Android client: https://github.com/2dust/v2rayNG
linux client with WebUi: https://github.com/v2rayA/v2rayA

Example Setting:
Vmess without tls
https://user-images.githubusercontent.com/98247050/169814131-73a32a4c-a4e8-48d7-981e-8747e6d07033.png
Vmess with tls
https://user-images.githubusercontent.com/98247050/169813997-36251e5c-d14c-4e55-a4b5-274b6ccc5e19.png
