### ISSUE TITLE
如何在aria2重启后不更新tracker或加入指定tracker

### ISSUE THREAD

**Issue by plok00286750** [wy580477/Leech-AIO-APP-EX#50]
如何在aria2重启后不更新tracker或加入指定tracker,我自己试过改aria2.conf,最后tracker部份,但重启后並非我修改的tracker

**Comment by wy580477** [comment]
https://github.com/wy580477/Leech-AIO-APP-EX/blob/main/content/service/2/run

注释掉 /workdir/aria2/tracker.sh /mnt/data/config/aria2.conf 2>/dev/null 这一行。

**Comment by wy580477** [comment]
> > https://github.com/wy580477/Leech-AIO-APP-EX/blob/main/content/service/2/run
> > 注释掉 /workdir/aria2/tracker.sh /mnt/data/config/aria2.conf 2>/dev/null 这一行。
> 
> 要重新配置吗?还是可以在explorer改

需要重新配置。
