### ISSUE TITLE
docker部署到局域网，打开qbittorrent报错，报错如截图

### ISSUE THREAD

**Issue by xyy55** [wy580477/Leech-AIO-APP-EX#54]
![image](https://user-images.githubusercontent.com/23710515/204532128-fd15403c-676d-467e-ad68-42399da0be65.png)

**Comment by wy580477** [comment]
第一次见到这个报错，开浏览器无痕浏览页面访问一下试试

**Comment by xyy55** [comment]
> 有没有见到登录框，有登陆框的话是用admin/adminadmin登陆的么。
> 
> 如果没见到登录框，开浏览器无痕浏览页面访问一下试试。
还是没见到登录框

**Comment by wy580477** [comment]
> 还是没见到登录框

删除这个配置文件，然后重启容器看看

![Screenshot_2022-12-01-01-40-49-068_com microsoft emmx](https://user-images.githubusercontent.com/98247050/204869637-eb50630a-0ea1-4b13-8f20-6b7d9e9c428f.png)
