### ISSUE TITLE
Plz Add Video education

### ISSUE THREAD

**Issue by turkishman41** [wy580477/Leech-AIO-APP-EX#55]
Bro , How can I install this on linux VPS ? Plz Add video education with code commands.

**Comment by wy580477** [comment]
On Debian/Ubuntu
```
apt install docker-ce docker-compose
wget https://raw.githubusercontent.com/wy580477/Leech-AIO-APP-EX/docker/docker-compose_en.yml
# Then edit docker-compose_en.yml file to suit your needs.
docker-compose -f docker-compose_en.yml up -d
```

**Comment by turkishman41** [comment]
Bro Thanks i install , just cannot run ,  
The counter has also been created.
What code should I enter for it?
Then in
docker-compos_en.yml
What information should I enter, will it be executed if I don't change it or should I change it?!

**Comment by wy580477** [comment]
> Bro Thanks i install , just cannot run , The counter has also been created. What code should I enter for it? Then in docker-compos_en.yml What information should I enter, will it be executed if I don't change it or should I change it?!

You need some basic linux skill.
```
# Use nano to edit docker-compose_en.yml file. There are detailed information to guide you for configing envs.
nano docker-compose_en.yml
# Delete old container and start new one
docker-compose -f docker-compose_en.yml down && docker-compose -f docker-compose_en.yml up -d
```

**Comment by turkishman41** [comment]
After entering the command codes,
IP vps/portal

Only nothing comes up

**Comment by wy580477** [comment]
> After entering the command codes, IP vps/portal
> 
> Only nothing comes up

You fill domain in CADDY_DOMAIN env or leave it blank?

**Comment by turkishman41** [comment]
Yes

**Comment by turkishman41** [comment]
> > Yes
> 
> If you have set domain as CADDY_DOMAIN env, you need to visit domain:port

No leave it

**Comment by wy580477** [comment]
> No leave it blank

I did a fresh install on a new opened VPS, can't reproduce you problem.

Post /config/log/caddy/current file under data folder which you set up in docker-compose file. To see if something prevents caddy web service from starting.

**Comment by turkishman41** [comment]
Hello 👋, How are you ?! I still haven't deployed this script on vps, why don't you post a training video?!
Many people may have a distribution problem,
