### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by rinrinx** [wy580477/Leech-AIO-APP-EX#56]
Bro i have unlimited account , is heroku currently banning your repo?

**Comment by rinrinx** [comment]
Thank you dir i am try today but heroku banned old time rclone

**Comment by aprils148** [comment]
heroku每天會重置嗎?

**Comment by wy580477** [comment]
> heroku每天會重置嗎?

记得是每24-27小时强制重启。重启后文件系统恢复回部署时状态。

**Comment by aprils148** [comment]
> > heroku每天會重置嗎?
> 
> 记得是每24-27小时强制重启。重启后文件系统恢复回部署时状态。

我看你的heroku部署文檔可以用Cloudflare KV避免這問題嗎?

**Comment by wy580477** [comment]
> > > heroku每天會重置嗎?
> > 
> > 
> > 记得是每24-27小时强制重启。重启后文件系统恢复回部署时状态。
> 
> 我看你的heroku部署文檔可以用Cloudflare KV避免這問題嗎?

对，会备份配置文件。
