### ISSUE TITLE
colab部署方式

### ISSUE THREAD

**Issue by wnbh** [wy580477/Leech-AIO-APP-EX#57]
麻烦更新一下colab部署方式，为其添加telegram-upload

**Comment by wy580477** [comment]
> 麻烦更新一下colab部署方式，为其添加telegram-upload

我现在有点犹豫，telegram-upload速度不理想，1MB-2MB/s，tdl速度很快但issue区有不少反映封号的，我想等等看tdl封号问题改进再折腾telegram上传工具。

**Comment by wnbh** [comment]
> > 麻烦更新一下colab部署方式，为其添加telegram-upload
> 
> 我现在有点犹豫，telegram-upload速度不理想，1MB-2MB/s，tdl速度很快但issue区有不少反映封号的，我想等等看tdl封号问题改进再折腾telegram上传工具。

不冲突，有更好的选择再把这个换掉就行了

**Comment by 8ty** [comment]
colab不是要一直开着浏览器才行吗
