### ISSUE TITLE
qbittorrent开启代理后自动上传报错

### ISSUE THREAD

**Issue by Kwok1am** [wy580477/Leech-AIO-APP-EX#59]
The requested URL returned error: 503
[ERROR] Failed to send job to rclone: /mnt/data/qbit_downloads/xxxx
进容器后手动执行qbittorclone.sh 能正常发送任务上传，有什么解决办法吗

**Comment by wy580477** [comment]
如果勾选上只对torrent使用代理呢？

**Comment by Kwok1am** [comment]
给几个localhost的加上--noproxy "*" 后正常了

**Comment by wy580477** [comment]
感谢分享解决成果。已经发布了修复此问题的 v1.6.8 版本。
