### ISSUE TITLE
如何部署到其他的平台？

### ISSUE THREAD

**Issue by 8ty** [wy580477/Leech-AIO-APP-EX#61]
比如replit或koyeb?

**Comment by wy580477** [comment]
部署别的平台不难，但问题是别的平台几乎都有流量限制，不适合跑大流量。

Heroku优势就是每个app每月2TB流量软上限。
Koyeb每月只有100G，Replit也是每月100G软上限。
我试过Northflank，文档没说有流量限制，但三天跑了500G以后号被封了。

**Comment by 8ty** [comment]
> 部署别的平台不难，但问题是别的平台几乎都有流量限制，不适合跑大流量。
> 
> Heroku优势就是每个app每月2TB流量软上限。 Koyeb每月只有100G，Replit也是每月100G软上限。 我试过Northflank，文档没说有流量限制，但三天跑了500G以后号被封了。

我找找看其他的看看。还有colab不是要一直开着浏览器才可以正常连接吗

**Comment by wy580477** [comment]
> 还有colab不是要一直开着浏览器才可以正常连接吗
是的

**Comment by 8ty** [comment]
所以应该怎么部署到别的平台呢？我试着用action构建推送到dockerhub上然后部署，不过没成功

**Comment by wy580477** [comment]
> 所以应该怎么部署到别的平台呢？我试着用action构建推送到dockerhub上然后部署，不过没成功

具体是啥平台，这是在猜谜么。

**Comment by 8ty** [comment]
> > 所以应该怎么部署到别的平台呢？我试着用action构建推送到dockerhub上然后部署，不过没成功
> 
> 具体是啥平台，这是在猜谜么。

不好意思，忘记说了，就是koyeb和Northflank，我感觉可以注册多几个然后弄成负载均衡

**Comment by 8ty** [comment]
> > 所以应该怎么部署到别的平台呢？我试着用action构建推送到dockerhub上然后部署，不过没成功
> 
> 具体是啥平台，这是在猜谜么。

还有一个就是doprax.com，官方说无限流量，不过我直接导入部署失败了

**Comment by wy580477** [comment]
> 还有一个就是doprax.com，官方说无限流量，不过我直接导入部署失败了

Koyeb不想搞，和Heroku比没啥优势，不如搞个Github学生包继续嫖Heroku。

Northflank需要绑卡，而且CPU龟速，Rclone跑到10MB/s就差不多占满了，还会封号，不想折腾了。

Doprax这两天我会搞一下试试看风控怎么样。

**Comment by 6uu1** [comment]
> > 还有一个就是doprax.com，官方说无限流量，不过我直接导入部署失败了
> 
> Koyeb不想搞，和Heroku比没啥优势，不如搞个Github学生包继续嫖Heroku。 你要是想折腾的话，从docker分支里面有github action，复制到你fork的库里，新建一个版本为'v1.0.0'的release就会自动运行生成镜像。 Koyeb部署的时候应该是需要有一个PORT变量。
> 
> Northflank需要绑卡，而且CPU龟速，Rclone跑到10MB/s就差不多占满了，还会封号，不想折腾了。 你要是想折腾的话，Northflank支持持久数据卷，不需要使用KV备份数据，直接用docker分支生成镜像应该就能用。 部署的时候，加一个持久数据卷，挂载到/mnt/data/config。 但docker分支没做进程名伪装，可能封号风险会更高，可以自己去/content/service里面服务脚本改下执行文件名。
> 
> Doprax这两天我会搞一下试试看风控怎么样。
> 
> 在Doprax容器里面跑了下speedtest，这网速感觉有点炸啊。。。
> 
> ![image](https://user-images.githubusercontent.com/98247050/212674568-c0e73f01-abfc-41c8-b323-b46000b10012.png)

哦好的。
doprax我刚开始看感觉还好啊，机器500mb的口子有时测速跑满。应该不错。
那个port的变量填哪个？还有请问，内部容器的镜像端口又是哪个

**Comment by wy580477** [comment]
>  那个port的变量填哪个？还有请问，内部容器的镜像端口又是哪个

PORT变量随意，8080之类就行。main分支，容器内部web端口直接引用PORT变量的。

**Comment by wy580477** [comment]
> 还有一个就是doprax.com，官方说无限流量，不过我直接导入部署失败了

Doprax 部署搓好了：https://github.com/wy580477/Leech-AIO-APP-EX/blob/main/docs/README_doprax_chs.md

这个 Doprax 分支其实适用于 Northflank，我没写，怕有人绑卡账户被封了来说三道四。
