### ISSUE TITLE
Rclone won't upload files

### ISSUE THREAD

**Issue by scese250** [wy580477/Leech-AIO-APP-EX#63]
After the file is downloaded, the Rclone web GUI shows that the file is being uploaded, but it stucks at 0%. As intended, it creates an "upload" folder on my G.Drive and I double checked that the rclone.config is valid. I haven't used this script in a month, it worked before so I updated the script and it still doesn't work. No error log from the Rclone web GUI.

**Comment by wy580477** [comment]
Post your downloader log. To see if the scrpt sent correct job imformation to Rclone.

**Comment by scese250** [comment]
Here is my log while downloading qBittorrent and a screenshot of the rclone web gui
![image](https://user-images.githubusercontent.com/12405564/213355452-fa99903a-bf9a-4e61-8635-9d4ebf90137b.png)


[log.zip](https://github.com/wy580477/Leech-AIO-APP-EX/files/10453550/log.zip)

**Comment by wy580477** [comment]
> Here is my log while downloading qBittorrent and a screenshot of the rclone web gui !

I can't reproduce your problem, the script is working fine on my google drive.

![image](https://user-images.githubusercontent.com/98247050/213385404-b1f72c0d-de26-453a-8406-dad6cf3006a9.png)

I think it's more likely a Rclone problem. 
Did you use your own client_id? 
Have you tried to create a new google drive config?
Or perhaps something went wrong in your network?

**Comment by scese250** [comment]
It was my end. Looks like the API has issues with the limit... 

"googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded".
