### ISSUE TITLE
where to find template repository?

### ISSUE THREAD

**Issue by gosndka** [wy580477/Leech-AIO-APP-EX#67]
![image](https://user-images.githubusercontent.com/92586328/214794234-3eaf6fc2-0e4d-40b2-bf7f-04f2b5bd1948.png)
Hello, I know how to fork but what do you mean by  click Setting on fork repository page and check Template repository.
Click new button: Use this template，create a new repository。I don't seem to find any setting when I try to fork the repo.
Can anyone help me out?

![image](https://user-images.githubusercontent.com/92586328/214794975-3df0a00e-0353-4db3-923c-1f3a3cfe6871.png)

**Comment by wy580477** [comment]
First, click create fork. Then look here.

![image](https://user-images.githubusercontent.com/98247050/214816355-944ed4dc-f092-4bac-ae89-1183d3f46c8a.png)

**Comment by gosndka** [comment]
> First, click create fork. Then look here.
> 
> ![image](https://user-images.githubusercontent.com/98247050/214816355-944ed4dc-f092-4bac-ae89-1183d3f46c8a.png)

Okay thanks should I only check the template section? I am unable to find understand the next step that is the second point

**Comment by wy580477** [comment]
> Okay thanks should I only check the template section? I am unable to find understand the next step that is the second point

Just check the template section, a new "Use this template" button will show up in your fork repo.

**Comment by gosndka** [comment]
> > Okay thanks should I only check the template section? I am unable to find understand the next step that is the second point
> 
> Just check the template section. Then go back to "Code" tab, a new "Use this template" button will show up in your fork repo.

Thank you so much for the help. Appreciate it

**Comment by gosndka** [comment]
@wy580477 getting error while opening on doprax
![image](https://user-images.githubusercontent.com/92586328/216422422-c3fcaf5b-9236-4348-b2f0-191ad8240af7.png)

**Comment by wy580477** [comment]
> @wy580477 getting error while opening on doprax ![image](https://user-images.githubusercontent.com/92586328/216422422-c3fcaf5b-9236-4348-b2f0-191ad8240af7.png)

It's likely due to high load on Doprax's servers.

![Screenshot_2023-02-03-05-40-09-529_com microsoft emmx dev](https://user-images.githubusercontent.com/98247050/216455944-12dcb673-eb00-4296-86b6-dd700654a775.png)

**Comment by gosndka** [comment]
> > @wy580477 getting error while opening on doprax ![image](https://user-images.githubusercontent.com/92586328/216422422-c3fcaf5b-9236-4348-b2f0-191ad8240af7.png)
> 
> It's likely due to high load on Doprax's servers.
> 
> ![Screenshot_2023-02-03-05-40-09-529_com microsoft emmx dev](https://user-images.githubusercontent.com/98247050/216455944-12dcb673-eb00-4296-86b6-dd700654a775.png)

I see but how does one check this?

**Comment by gosndka** [comment]
> > I see but how does one check this? And I checked the logs and it shows like this
> > ![image](https://user-images.githubusercontent.com/92586328/216521011-5eaaa8a7-1baf-4a34-801d-316e6f37acf4.png)
> 
> You deployed wrong branch. Use Doprax branch.

![image](https://user-images.githubusercontent.com/92586328/216609483-0e2a70a0-c2fd-4362-b57b-e9c25ccba30c.png)

**Comment by wy580477** [comment]
> ![image](https://user-images.githubusercontent.com/92586328/216609483-0e2a70a0-c2fd-4362-b57b-e9c25ccba30c.png)

Did a little fix: https://github.com/wy580477/Leech-AIO-APP-EX/commit/b5c47b765f0016a6726b0f216b095913941c33f1

**Comment by gosndka** [comment]
@wy580477 It seems that other users app are working while mine shows gateway timeout, any help
![gbn](https://user-images.githubusercontent.com/92586328/216922959-3447af1a-6764-4738-9916-2cc7d27e0762.jpg)

**Comment by wy580477** [comment]
> @wy580477 It seems that other users app are working while mine shows gateway timeout, any help

I also encountered 503 error. It's likely that Doprax service has degraded due to high load.

**Comment by gosndka** [comment]
> > @wy580477 It seems that other users app are working while mine shows gateway timeout, any help
> 
> I also encountered 503 error. It's likely that Doprax service has degraded due to high load.

Then doprax is dead too?

**Comment by wy580477** [comment]
> Then doprax is dead too?

It probably either has to enforce strict resource usage limit or goes down. I don't see their current bussiness strategy could last long.

**Comment by wy580477** [comment]
> They are asking for my app url, can I share it with them? Since they could easily trace it to back to this repo, wouldn't they ban it?

I have added cloudflared to doprax branch, so user can use cloudflared tunnel to bypass doprax's HTTP Router.

You will need a domain managed by cloudflare, test.test for example.

 1. Download  [Cloudflared](https://github.com/cloudflare/cloudflared/releases)
 
 2. Run "cloudflared login", then it will give a link for binding your domian.

 3. Run "cloudflared tunnel create <tunnel name>", then it will generate a JSON file.
    ```
    cloudflared tunnel create mytunnel
    ``` 
 4. Run "cloudflared tunnel route dns <tunnel name> tunnel.test.test", this will add a cname record. You can choose any third-level domain as you want.
    ```
    cloudflared tunnel route dns mytunnel mytunnel.test.test
    ```  
 5. During Deployment, add two environment variables:  "ArgoDOMAIN" and "ArgoJSON".
     Fill json file content in ArgoJSON env and set ArgoDOMAIN env to the domain which was set in step 4.

**Comment by wy580477** [comment]
> cloudlfared is only for linux, I use windows so can't really test this out

Emm......
 
https://github.com/cloudflare/cloudflared/releases/download/2023.2.1/cloudflared-windows-amd64.exe

**Comment by gosndka** [comment]
> > cloudlfared is only for linux, I use windows so can't really test this out
> 
> Emm......
> 
> https://github.com/cloudflare/cloudflared/releases/download/2023.2.1/cloudflared-windows-amd64.exe

![image](https://user-images.githubusercontent.com/92586328/218251882-12e719ad-0314-4fa3-8266-e3eafae96a25.png)

My bad, didn't see the complete page

**Comment by wy580477** [comment]
> Also what should I do here? didn't understand the 2nd step
> 
> ![image](https://user-images.githubusercontent.com/92586328/218252114-96da9a76-547e-468a-84db-8996b63269bd.png)

You need to have a domain on Cloudflare.

**Comment by gosndka** [comment]
> > Also what should I do here? didn't understand the 2nd step
> > ![image](https://user-images.githubusercontent.com/92586328/218252114-96da9a76-547e-468a-84db-8996b63269bd.png)
> 
> You need to have a domain on Cloudflare.

Well, damn. Is there no free alternative?

**Comment by wy580477** [comment]
> Well, damn. Is there no free alternative?

Since freenom is going to die， the only free way left is eu.org.
