### ISSUE TITLE
error while deploying

### ISSUE THREAD

**Issue by axhur** [wy580477/Leech-AIO-APP-EX#68]
Step 1/6 : FROM python:alpine

---> 407b57cd39cc

Step 2/6 : COPY ./content /workdir/

---> Using cache

---> a2b5beea4ec1

Step 3/6 : RUN apk add --no-cache curl caddy jq bash runit tzdata ttyd p7zip findutils wget && chmod +x /workdir/service/*/run /workdir/service/*/log/run /workdir/*.sh && /workdir/install.sh && rm -rf /workdir/install.sh /tmp/* ${HOME}/.cache ${HOME}/.cargo

---> Using cache

---> 4ca78467c97d

Step 4/6 : ENV PORT=3000

---> Using cache

---> f00ac8f02532

Step 5/6 : EXPOSE 3000

---> Using cache

---> 74e012be75f9

Step 6/6 : ENTRYPOINT ["sh","/workdir/entrypoint.sh"]

---> Using cache

---> b4cb921b7934

Successfully built b4cb921b7934

Successfully tagged registry.doprax.com:5000/agthsvg/oxfda3vbrh0k5gsifnqcgoioe9ccfd:latest

Process failed.

Can anyone help me out?

**Comment by wy580477** [comment]
> Can anyone help me out?

Try again. The container image is already built, either it's a problem from Doprax or Doprax has banned certain image layer.

**Comment by axhur** [comment]
> > Can anyone help me out?
> 
> Try again. The container image is already built, either it's a problem from Doprax or Doprax has banned certain image layer.
> 
> You can add some meanless code in your repo, then pull new changes in your Doprax dashboard. So Doprax has to rebuild image instead of using cache.

where should I add the code to the main repo or to doprax branch? And what kind of code?

**Comment by wy580477** [comment]
> where should I add the code to the main repo or to doprax branch? And what kind of code?

To Doprax brach. Any code would work, even a txt file works.

**Comment by axhur** [comment]
> > where should I add the code to the main repo or to doprax branch? And what kind of code?
> 
> To Doprax brach. Any changes would work, even adding a txt file works.

Okay, thanks for the help
