### ISSUE TITLE
deployed on AWS Ubuntu and can't access to app

### ISSUE THREAD

**Issue by KevinNitroG** [wy580477/Leech-AIO-APP-EX#71]
I'm needing help 😓

I have an AWS EC2 Ubuntu Instance and run those commands:
```
touch docker-compose_en.yml
vi docker-compose_en.yml
(enter the code...)
sudo snap install docker
sudo chmod 666 /var/run/docker.sock
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw status enable

docker-compose -f docker-compose_en.yml up -d
```
Then I access the app through `https://[my_EC2_instance_ip]/portal` but it showed this
![image](https://user-images.githubusercontent.com/86353526/216780041-13898fd2-03f3-4992-b226-a02fe30d0044.png)
Sorry I don't have much experience in using vps, docker and coding... 😓😓

**Comment by wy580477** [comment]
Nowadays browsers force ssl connection on default. 

Get a domain name point to your vps ip. Then fill the domain name in CADDY_DOMAIN env, caddy will enable auto-https. You don't need to buy a domain. Free ddns service domain works too.

**Comment by KevinNitroG** [comment]
Thank you I will try it
If it works I will close the this 🥰🥰
