### ISSUE TITLE
Serve On Specific Port

### ISSUE THREAD

**Issue by hehenaice** [wy580477/Leech-AIO-APP-EX#72]
This is a personal use case issue, where instead of serving the app on `<vps-ip>/portal` I need to serve it to `<vps-ip>:<specified-port>/portal`.
Please guide me through this minor issue of mine 

Thank you

**Comment by wy580477** [comment]
> This is a personal use case issue, where instead of serving the app on `<vps-ip>/portal` I need to serve it to `<vps-ip>:<specified-port>/portal`. Please guide me through this minor issue of mine
> 
> Thank you

You can specific port by changing CADDY_WEB_PORT env.

**Comment by hehenaice** [comment]
Hi
Thank you for your feedback.
I used `CADDY_DOMAIN: http://localhost` & 
`CADDY_WEB_PORT: 6000` ensuring http serve.
But it seems to be returning a blank white screen. I don't think I changed anything in particular. Except the mentioned vars, is there a way to debug this?

**Comment by wy580477** [comment]
> Hi Thank you for your feedback. I used `CADDY_DOMAIN: http://localhost` & `CADDY_WEB_PORT: 6000` ensuring http serve. But it seems to be returning a blank white screen. I don't think I changed anything in particular. Except the mentioned vars, is there a way to debug this?

Leave CADDY_DOMAIN blank.

**Comment by hehenaice** [comment]
That worked perfectly.
And yes, I'm intended to add this thing to my cloudflared config. 
Easy way to get SSL without ssl

**Comment by hehenaice** [comment]
Thanks again for the wonderful support and quick responses.
![IMG_20230205_132433_044](https://user-images.githubusercontent.com/82583245/216807919-8a5a569b-6ce0-432f-a11d-6c783a3b5947.jpg)
