### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by yiviseris** [wy580477/Leech-AIO-APP-EX#73]
i'm deploying with docker and i set blank for CADDY_DOMAIN and CADDY_WEB_PORT to 443. how to access it? which ip address is meant? my vps ip or which one?

**Comment by wy580477** [comment]
Use your vps ip addr.

You shoud get a domain which points to your vps ip and fill it in CADDY_DOMAIN, so caddy can properly enable auto-https which is more secure.

You don't need to buy a domain. Free ddns service domain works too.

**Comment by yiviseris** [comment]
![image](https://user-images.githubusercontent.com/107087281/217984932-297f1ad9-5da7-4621-94b0-eaf5cf2fe37a.png)
and the result is
![image](https://user-images.githubusercontent.com/107087281/217985036-139404c4-6b07-4bbb-a49f-482055ec5098.png)

**Comment by wy580477** [comment]
> ![image](https://user-images.githubusercontent.com/107087281/217984932-297f1ad9-5da7-4621-94b0-eaf5cf2fe37a.png) and the result is ![image](https://user-images.githubusercontent.com/107087281/217985036-139404c4-6b07-4bbb-a49f-482055ec5098.png)

Do not add http://. Just use "xxxx.ddns.net"

**Comment by yiviseris** [comment]
ah thank you bro, and it's worked, thank you so much

**Comment by wy580477** [comment]
> ah thank you bro, and it's worked, thank you so much. and where to setting the qbittorent user and password?

 In qbit offical web ui, Tools > options > WEB UI > Authentication.

**Comment by yiviseris** [comment]
sorry i'm bother you, and where's the default username:password for ariang and rclone?

**Comment by wy580477** [comment]
> sorry i'm bother you, and where's the default username:password for ariang and rclone?

It‘s the same with portal page.
