### ISSUE TITLE
cloudflared出不了地址

### ISSUE THREAD

**Issue by 362227** [wy580477/Leech-AIO-APP-EX#79]
cloudflared出不了地址了，有几小时了

**Comment by wy580477** [comment]
![image](https://user-images.githubusercontent.com/98247050/222125978-e674e047-6d65-43a9-85e6-10ad7bfb973d.png)

Cloudflare的问题，我在vps上试用隧道也开不了。要是等两天还不好，我再搞搞其它内网穿透方案。

**Comment by 362227** [comment]
已恢复正常
