### ISSUE TITLE
How to avoid one drive throttling limit

### ISSUE THREAD

**Issue by Th4Park** [wy580477/Leech-AIO-APP-EX#8]
I copied only 20 GB, after that it got blocked, after 10 hours try again, it is showing

**Comment by wy580477** [comment]
Do not view videos via onedrive offical web page.

Transcoding will get you throttled very quickly.

**Comment by Th4Park** [comment]
But I haven't seen any video till now, please solve this problem only.

https://forum.rclone.org/t/rclone-v1-55-1-throttling-and-worse-on-onedrive-copy-to-gd/25018/6

**Comment by wy580477** [comment]
Getting your own Client ID and Key

https://rclone.org/onedrive/#getting-your-own-client-id-and-key

**Comment by Th4Park** [comment]
I use my own credentials but then the same problem comes
