### ISSUE TITLE
docker装上打不开

### ISSUE THREAD

**Issue by f63531119** [wy580477/Leech-AIO-APP-EX#80]
后台可以看到有运行 IP端口加路径 打不开

**Comment by f63531119** [comment]
docker logs -f allinone 日志显示这个
Docker version 23.0.1, build a5ee5b1
Docker Compose version v2.16.0
是不是少依赖

**Comment by wy580477** [comment]
让你发docker-composea设置和网页打不开的截图，你也不发，帮不了你了。

**Comment by f63531119** [comment]
默认配置就改下账号密码 /路径

**Comment by wy580477** [comment]
> 默认配置就改下账号密码 /路径

最后回复一次，你的描述我什么都听不懂，我只能看懂截图。

**Comment by wy580477** [comment]
大半夜血压上来了，关了睡觉。
不发网页截图我怎么知道是caddy没跑起来还是路径错误？
不发docker-compose设置我怎么知道里面有没有设置错误？我又不能坐在你屏幕边上帮你debug，请你发个屏幕截图都要不来。
