### ISSUE TITLE
back4app 部署时无法访问

### ISSUE THREAD

**Issue by 2451965602** [wy580477/Leech-AIO-APP-EX#82]
用heroku方法部署的

日志

2023-03-15T11:52:27.334Z7b87f575mv: can't rename '/workdir/1*': No such file or directory

2023-03-15T11:52:28.344Z7b87f575mv: can't rename '/workdir/1*': No such file or directory

**Comment by 2451965602** [comment]
网页截图 https://alist.yourang.top/d/onedrive%205t/%E7%BD%91%E9%A1%B5%E6%8D%95%E8%8E%B7_15-3-2023_195447_heroku-2451965602.b4a.run.jpeg?sign=C4M_QTWYNTsA75JuqpDAtlvPsDWdtAj4EdY1dGPDXzs=:0

**Comment by wy580477** [comment]
back4app 的 http 路由向容器传递了错误的 X-Forwarded-Proto，导致了重定向循环。

解决办法：

在仓库 /content/Caddyfile 文件中删除下面内容：
```
	# Redirect http to https
	@http-req {
		header X-Forwarded-Proto http
	}
	redir @http-req https://{host}{uri}
```

另外，256MB内存运行这个容器有点勉强，空闲内存应该剩下不到100MB。
可以考虑把 content/service 目录下的 5 和 6 两个目录删掉，这样不会运行 rclone webdav 和 pyload，可以节省出几十MB内存。

back4app 似乎是不支持 websocket 的， aria2 无法以 wss 方式连接，ttyd 也无法使用。

**Comment by 2451965602** [comment]
感谢
