### ISSUE TITLE
Docker版每个服务独立启停应该怎样操作

### ISSUE THREAD

**Issue by Saniadoajd** [wy580477/Leech-AIO-APP-EX#83]
Doker版提到基于 runit的进程管理，每个服务可以独立启停。请问具体如何操作，主要是有些服务不太用得上

**Comment by wy580477** [comment]
> Doker版提到基于 runit的进程管理，每个服务可以独立启停。请问具体如何操作，主要是有些服务不太用得上

docker exec sv stop <服务名>

服务名有下面这些：
![image](https://user-images.githubusercontent.com/98247050/226099759-cfd62dff-9be9-4086-940e-77f47b858101.png)
