### ISSUE TITLE
rclone在上传办公文件（word、xls等）和html文档的时候报错

### ISSUE THREAD

**Issue by vtstojs** [wy580477/Leech-AIO-APP-EX#84]
rclone在上传这些文件可能会报错：
corrupted on transfer: sizes differ 6819866 vs 6827187

建议加上--ignore-checksum --ignore-size忽略文件检查指令，强制拷贝。

**Comment by wy580477** [comment]
> rclone在上传这些文件可能会报错： corrupted on transfer: sizes differ 6819866 vs 6827187
> 
> 建议加上--ignore-checksum --ignore-size忽略文件检查指令，强制拷贝。

config目录下有rclone_options.conf文件，里面可以加rclone的选择。

**Comment by vtstojs** [comment]
> > rclone在上传这些文件可能会报错： corrupted on transfer: sizes differ 6819866 vs 6827187
> > 建议加上--ignore-checksum --ignore-size忽略文件检查指令，强制拷贝。
> 
> config目录下有rclone_options.conf文件，里面可以加rclone的选项。

好的，谢谢大佬
