### ISSUE TITLE
我用服务器 ip 将它部署在我的 vps 上，并使用 /portal 这是 beast soo ip/beast 但看不到它工作。

### ISSUE THREAD

**Issue by BeastAnimation361** [wy580477/Leech-AIO-APP-EX#88]
我用服务器 ip 将它部署在我的 vps 上，并使用 /portal 这是 beast soo ip/beast 但看不到它工作。

**Comment by wy580477** [comment]
You can speak or translate to English, which would be easier for me to understand.

Give me a screenshot of your browser while you visit ip/portal.

**Comment by BeastAnimation361** [comment]
![image](https://user-images.githubusercontent.com/108323892/234840724-331b6c17-d597-4e40-93be-c0f77c62d9c6.png)
sorry lol i thought you were chines...soo..sorry lol

**Comment by wy580477** [comment]
> ![image](https://user-images.githubusercontent.com/108323892/234840724-331b6c17-d597-4e40-93be-c0f77c62d9c6.png) 

I'm indeed Chinese. It's just than machine translation is usually bad for Chinese.

> ![image](https://user-images.githubusercontent.com/108323892/234840724-331b6c17-d597-4e40-93be-c0f77c62d9c6.png) 

Make sure that you server port 8080 is open and CADDY_WEB_PORT is set to 8080.

**Comment by BeastAnimation361** [comment]
![image](https://user-images.githubusercontent.com/108323892/234841778-46296247-0bb0-422f-ac78-defc405325a3.png)
so i saw that org port was 443 so i used that and this is what it shows

**Comment by BeastAnimation361** [comment]
bro now its showing this
Client sent an HTTP request to an HTTPS server.
after i changed the 8080 to 443
it must be 8080 port?

**Comment by wy580477** [comment]
> so i saw that org port was 443 so i used that and this is what it shows

I would recommend that you get a domain name and point it to your server ip.

Then set CADDY_DOMAIN to your domain name. 

After above steps, caddy will enabel auto-https which is more secure.

If you insist to visit with ip, use https://< your ip >:443/your-path

**Comment by BeastAnimation361** [comment]
bro any website to get free domain and also i tried https://< your ip >:443/your-path doesnot load up

**Comment by wy580477** [comment]
> i tried https://< your ip >:443/your-path doesnot load up

Plz，give more info. What error? Don't make me guessing for you....

> bro any website to get free domain

You can try < your server ip >.nip.io,  such as 22.22.22.22.nip.io

**Comment by BeastAnimation361** [comment]
so i tried nip.io and this came up
![image](https://user-images.githubusercontent.com/108323892/234843746-0eafd483-5047-4ed2-aa16-a0be05df5224.png)

and also https://< your ip >:443/your-path doesnot load up
![image](https://user-images.githubusercontent.com/108323892/234843905-dacfa7f5-fec2-4f31-9aa4-26a30120659f.png)

**Comment by BeastAnimation361** [comment]
sorry bro i am noob at this. really new to this docker. i think i made mistake in deploying it?
i download your repo and changed the portal in docker-compose_en and then docker up cammand

**Comment by wy580477** [comment]
Well, I don't have time to debug ssl problem for your now.

Change CADDY_WEB_PORT to 8080, then open 8080 port in your firewall setting. This should be working at http://< your server ip >:8080/your-path.

**Comment by BeastAnimation361** [comment]
...bro u gonna leave me hanging bro i am trying to deploy the best mirror app and u gonna leave me hanging because i am black? sheeh...joke brooo kk but any other tip to fix it

**Comment by BeastAnimation361** [comment]
bro how do i open 8080 port in your firewall setting.
in putty?

**Comment by wy580477** [comment]
> bro how do i open 8080 port in your firewall setting. in putty?

I don't know. Ask your vps service provider

**Comment by BeastAnimation361** [comment]
ok bro thanks but might have to contact u again sorry for being pain in ass.

**Comment by BeastAnimation361** [comment]
bro all ports are open in firewall...please can u guide me i think i messed up while deplying it

**Comment by wy580477** [comment]
> bro all ports are open in firewall...please can u guide me i think i messed up while deplying it

I can't help if you keep screaming at me without providing any info.

**Comment by BeastAnimation361** [comment]
how can i send logs? u got tele? discord where i can send all the private file.

**Comment by wy580477** [comment]
> how can i send logs? u got tele? discord where i can send all the private file.

Just paste it here after editing out personal info.

**Comment by wy580477** [comment]
> > Just paste it here after editing out personal info.
> 
> i mean like...how do i get logs from putty

google is your friend. I'm not your basic linux skill teacher

**Comment by BeastAnimation361** [comment]
root@instance-2:/home/beast# cd leech
root@instance-2:/home/beast/leech# docker-compose up 
Starting allinone ... done

**Comment by BeastAnimation361** [comment]
> root@instance-2:/home/beast# cd leech root@instance-2:/home/beast/leech# docker-compose up Starting allinone ... done

hope this helps so i started docker again

**Comment by BeastAnimation361** [comment]
sorry . so i tried to get logs from docker and this is what i got

`
Fetch the logs of a container
root@instance-2:/home/bhadoo/leech# docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED       STATUS          PORTS     NAMES
9d6c6887a9cd   ghcr.io/wy580477/leech-aio-app-ex:latest   "sh -c /workdir/entr…"   2 hours ago   Up 44 seconds             allinone
root@instance-2:/home/bhadoo/leech# docker logs 9d6c6887a9cd
root@instance-2:/home/bhadoo/leech# docker logs 9d6c6887a9cd
root@instance-2:/home/bhadoo/leech# docker logs -f 9d6c6887a9cd
`

**Comment by wy580477** [comment]
Why don't you post your browser error？ Is it some state top secret which would get you killed? 

I'm closing this now. Since I already tell you to provide errors, and you wouldn't listen.

**Comment by BeastAnimation361** [comment]
![image](https://user-images.githubusercontent.com/108323892/234859342-32ba9fd3-3225-445c-8245-cdee8cdf378b.png)

**Comment by BeastAnimation361** [comment]
this is what it shows .so i even tried changing the port to 8080 but then it shows nothing just 
![image](https://user-images.githubusercontent.com/108323892/234859601-00e34d34-619f-4f1d-bc60-54d9a02e8bdf.png)

so i changed port back to 443

**Comment by BeastAnimation361** [comment]
bro you are there?

**Comment by wy580477** [comment]
> this is what it shows .so i even tried changing the port to 8080 but then it shows nothing just 

Either your port 8080 is closed or you didn't change CADDY_WED_PORT to 8080. Did you recreate container after changing docker-compose env? You need to recreate containter for new env to take effect.

docker-compose up -d --force-recreate

> so i changed port back to 443

If you want to use 443 port, go to namesilo, buy a .top domain only 1 dollar per year. Problem sovled.

My last reply. Bye~
