### ISSUE TITLE
Docker deployment 

### ISSUE THREAD

**Issue by arjung24** [wy580477/Leech-AIO-APP-EX#89]
Please help. I did according to the guideline. But when opening ip  it's not working. Please see attached file. Is there anything wrong in my docker-compose_en.yml file.
![IMG_20230428_214059](https://user-images.githubusercontent.com/68998000/235192708-e012f40a-dc37-4905-a11d-8cb910aefaab.jpg)

**Comment by arjung24** [comment]
![IMG_20230428_222435_000](https://user-images.githubusercontent.com/68998000/235207049-430d291d-9119-475f-aa91-530dcfdb584d.jpg)

**Comment by arjung24** [comment]
![IMG_20230428_232854](https://user-images.githubusercontent.com/68998000/235214407-9cc85964-96be-4bd8-baee-59b242ddd80c.jpg)

**Comment by arjung24** [comment]
![IMG_20230428_233655](https://user-images.githubusercontent.com/68998000/235217117-cfc89641-c1e7-42ba-82ba-d01ca9f298f0.jpg)

**Comment by arjung24** [comment]
![IMG_20230428_234642_022](https://user-images.githubusercontent.com/68998000/235217874-11cc5d50-e8e2-42fb-bbd0-95b1e4c92ff9.jpg)
![IMG_20230428_234455](https://user-images.githubusercontent.com/68998000/235217878-7756d1e6-7bc0-480a-bdbb-a272928bb275.jpg)

**Comment by arjung24** [comment]
I tried every possible way brother. But it's not working. Will u please help me

**Comment by wy580477** [comment]
> ![IMG_20230428_232854](https://user-images.githubusercontent.com/68998000/235214407-9cc85964-96be-4bd8-baee-59b242ddd80c.jpg)

If you use http protocol， change to a non-443 port.

**Comment by wy580477** [comment]
> ![IMG_20230428_234642_022](https://user-images.githubusercontent.com/68998000/235217874-11cc5d50-e8e2-42fb-bbd0-95b1e4c92ff9.jpg) ![IMG_20230428_234455](https://user-images.githubusercontent.com/68998000/235217878-7756d1e6-7bc0-480a-bdbb-a272928bb275.jpg)

Check you domain dns record, browser told you it can't find ip addr.

**Comment by arjung24** [comment]
> > ![IMG_20230428_234642_022]
> 
> Check you domain dns record, browser told you it can't find ip addr.

![IMG_20230429_064654](https://user-images.githubusercontent.com/68998000/235273793-91b8be0e-b96e-485b-8976-de24c1974cac.jpg)

**Comment by wy580477** [comment]
> > > ![IMG_20230428_234642_022]
> > 
> > 
> > Check you domain dns record, browser told you it can't find ip addr.
> 
> ![IMG_20230429_064654](https://user-images.githubusercontent.com/68998000/235273793-91b8be0e-b96e-485b-8976-de24c1974cac.jpg)

add your sub-domain to your record.....

**Comment by arjung24** [comment]
Dns records telling that it's active

**Comment by arjung24** [comment]
> > > > ![IMG_20230428_234642_022]
> > > 
> > > 
> > > Check you domain dns record, browser told you it can't find ip addr.
> > 
> > 
> > ![IMG_20230429_064654](https://user-images.githubusercontent.com/68998000/235273793-91b8be0e-b96e-485b-8976-de24c1974cac.jpg)
> 
> add your sub-domain to your record.....

Okay. Will try that. Thanks

**Comment by wy580477** [comment]
> Okay. Will try that. Thanks My sub domain wil be like this my-server-ip.jmirror.tech or anything else

whatever-you-want.jmirror.tech

**Comment by arjung24** [comment]
> > Okay. Will try that. Thanks My sub domain wil be like this my-server-ip.jmirror.tech or anything else
> 
> whatever-you-want.jmirror.tech

Thanks brother. Will try and let u know

**Comment by arjung24** [comment]
> > Okay. Will try that. Thanks My sub domain wil be like this my-server-ip.jmirror.tech or anything else
> 
> whatever-you-want.jmirror.tech

![IMG_20230429_074736](https://user-images.githubusercontent.com/68998000/235278084-d72208ee-3c56-4432-a966-3239a01caa28.jpg)
Still not working brother

**Comment by arjung24** [comment]
> ![IMG_20230428_234642_022](https://user-images.githubusercontent.com/68998000/235217874-11cc5d50-e8e2-42fb-bbd0-95b1e4c92ff9.jpg) ![IMG_20230428_234455](https://user-images.githubusercontent.com/68998000/235217878-7756d1e6-7bc0-480a-bdbb-a272928bb275.jpg)

Showing like this again

**Comment by wy580477** [comment]
> Showing like this again

.... why don't you visit your new sub-domain? You set up a new subdomain, then of course you need to use new sub-domain to reach it.

And you need to change CADDY_DOMAIN to your new sub-domain, then recreate the container.

For fxxk's sake, I'm considering removing https support altogather since it seems to hard for lots of ppl.

**Comment by arjung24** [comment]
> > Showing like this again
> 
> .... why don't you visit your new sub-domain? You set up a new subdomain, then of course you need to use new sub-domain to reach it.
> 
> And you need to change CADDY_DOMAIN to your new sub-domain, then recreate the container.
> 
> For fxxk's sake, I'm considering removing https support altogather since it seems to hard for lots of ppl.

I did both 😔
![IMG_20230429_080001](https://user-images.githubusercontent.com/68998000/235278418-b65e8854-7ce8-40a4-a3d4-fb5d56c488bf.jpg)

**Comment by wy580477** [comment]
> I did both 😔 ![IMG_20230429_080001](https://user-images.githubusercontent.com/68998000/235278418-b65e8854-7ce8-40a4-a3d4-fb5d56c488bf.jpg)

You dns record is not working. Not my problem. Ask you dns service provider.
