### ISSUE TITLE
关于Cloudflare Workers反代绕过Heroku非信用卡认证账号每月550小时限制

### ISSUE THREAD

**Issue by plok00286750** [wy580477/Leech-AIO-APP-EX#9]
2个域名
A.herokuapp.com
B.herokuapp.com
第二天我用A域名,实际上连上的是B域名对吗?
另外aria2的RPC要改吗?

**Comment by wy580477** [comment]
- 一直用workers域名访问才会单双日交替。
- 两个dyno变量一样就不用换。
