### ISSUE TITLE
sorry me again. ttyd is not available when runing it on vps( how can i enable it?)

### ISSUE THREAD

**Issue by BeastAnimation361** [wy580477/Leech-AIO-APP-EX#90]
sorry me again. ttyd is not available when runing it on vps how can i enable it?

**Comment by wy580477** [comment]
I didn't include ttyd in docker deployment.

Logging into terminal via ssh is more secure than ttyd.

**Comment by BeastAnimation361** [comment]
fwk i need that.... any way to add it?

**Comment by BeastAnimation361** [comment]
bro if any way please do tell. i really wanted ttyd thats why i deplyed the leech bot.

**Comment by wy580477** [comment]
> fwk i need that.... any way to add it?

You can install ttyd on your vps directly. 

https://github.com/tsl0922/ttyd#install-on-linux

**Comment by BeastAnimation361** [comment]
do i have to buy a domain and then connect it to it. just for ttyd?

**Comment by BeastAnimation361** [comment]
is there any way i can edit the repo code and add ttyd in it?

**Comment by wy580477** [comment]
> do i have to buy a domain and then connect it to it. just for ttyd?

Not necessary. But i suggest you get a domain and enable https for ttyd. 

Guarding terminal access is very important for security.

**Comment by wy580477** [comment]
> is there any way i can edit the repo code and add ttyd in it?

You can. Not an easy task though.

Is there any reason that you can't access termial via normal SSH client?  Using SSH client would be more secure than ttyd.

**Comment by BeastAnimation361** [comment]
bro i don't give a f for security...and ssh is pain in ass when i am out like using from termix

**Comment by BeastAnimation361** [comment]
Hi soo i kinda half way added the ttyd but it's not showing in dashboard and i think it has to do something with this run file from ttyd folder
```

#!/bin/sh

exec 2>&1

if [ ! -f "/mnt/data/config/bashrc" ]; then
    cp /workdir/bashrc /mnt/data/config/
fi

TELEGRAM_TITLE="$(grep ^telegram-notification-title "/mnt/data/config/script.conf" | cut -d= -f2- | sed "s|^[ \t]*||g;s|\r$||")"

exec ttyd -i 127.0.0.1 -p 61808 -P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc

```
this line 
exec ttyd -i 127.0.0.1 -p 61808 -P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc

i changed it to 
`exec ttyd -i  "s|listenAddressSingleHTTPFrontend:.*|listenAddressSingleHTTPFrontend: 127.0.0.1:${OLIVETIN_PORT}|g"-P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc`
 but still now working
 any ideas?
thankss

**Comment by wy580477** [comment]
> Hi soo i kinda half way added the ttyd but it's not showing in dashboard and i think it has to do something with this run file from ttyd folder
> 
> ```
> 
> #!/bin/sh
> 
> exec 2>&1
> 
> if [ ! -f "/mnt/data/config/bashrc" ]; then
>     cp /workdir/bashrc /mnt/data/config/
> fi
> 
> TELEGRAM_TITLE="$(grep ^telegram-notification-title "/mnt/data/config/script.conf" | cut -d= -f2- | sed "s|^[ \t]*||g;s|\r$||")"
> 
> exec ttyd -i 127.0.0.1 -p 61808 -P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc
> ```
> 
> this line exec ttyd -i 127.0.0.1 -p 61808 -P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc
> 
> i changed it to `exec ttyd -i "s|listenAddressSingleHTTPFrontend:.*|listenAddressSingleHTTPFrontend: 127.0.0.1:${TTYD_PORT}|g"-P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc` but still now working any ideas? thankss

I said it wouldn't be easy. You need to add ttyd reverse proxy in Caddyfile, and add ttyd entry in homer config file.

**Comment by BeastAnimation361** [comment]
added homer config already
![image](https://user-images.githubusercontent.com/108323892/235300373-5bc65eff-a470-4bca-b1d6-ebf5e98d732c.png)
and also in caddy file
![image](https://user-images.githubusercontent.com/108323892/235300385-3ba52d65-8c36-4f2d-9098-922fa91f8b7e.png)

**Comment by wy580477** [comment]
> added homer config already 

press shift + f5 to force refresh. 

Have you installed ttyd yet? You need to run "apk add ttyd".

**Comment by BeastAnimation361** [comment]
still now showing up
btw these are the files i edited 
![image](https://user-images.githubusercontent.com/108323892/235300407-f2543d5e-347c-4050-b441-90e8b701d7c7.png)
and these is what i added in each one 
![image](https://user-images.githubusercontent.com/108323892/235300446-29e09771-8460-4670-a800-2c420a927ae7.png)

![image](https://user-images.githubusercontent.com/108323892/235300425-0c64b281-d1d9-4a61-8572-6aa15348c178.png)
![image](https://user-images.githubusercontent.com/108323892/235300460-56229985-2317-4f22-bdc3-d7b8315dc8f2.png)
![image](https://user-images.githubusercontent.com/108323892/235300464-4be79d5b-88e0-4b2a-a145-4f2b75572946.png)

**Comment by BeastAnimation361** [comment]
> > added homer config already
> 
> press shift + f5 to force refresh.
> 
> Have you installed ttyd yet? You need to run "apk add ttyd".

i did add all these edits and stop docker and then used 
 docker-compose up -d --force-recreate 
 and still it's not showing even tried /ttyd at then end not loading

**Comment by wy580477** [comment]
> still now showing up btw these are the files i edited 

You need to generate your own container image. 

Run "docker build . -t allinone" at this folder, then you can use your own container image "allinone".

**Comment by BeastAnimation361** [comment]
> > still now showing up btw these are the files i edited
> 
> You need to generate your own container image.
> 
> Run "docker build . -t allinone" at this folder, then you can use your own container image "allinone".

ok bro roger that.

**Comment by BeastAnimation361** [comment]
sorry new to docker stuff

**Comment by BeastAnimation361** [comment]
btw should i add this 
`exec ttyd -i "s|listenAddressSingleHTTPFrontend:.*|listenAddressSingleHTTPFrontend: 127.0.0.1:${TTYD_PORT}|g"-P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc`
or just keep it to 
`this line exec ttyd -i 127.0.0.1 -p 61808 -P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc

`

**Comment by wy580477** [comment]
> btw should i add this 

exec ttyd -i 127.0.0.1 -p ${TTYD_PORT} -P 3 -t fontSize=17 -t titleFixed=${TELEGRAM_TITLE}_ttyd -t 'theme={"background": "black"}' bash --rcfile /mnt/data/config/bashrc

**Comment by BeastAnimation361** [comment]
![image](https://user-images.githubusercontent.com/108323892/235301072-4b7cf387-e5f6-4c9f-b7a2-d11ff03ea446.png)
still now working

**Comment by wy580477** [comment]
> ![image](https://user-images.githubusercontent.com/108323892/235301072-4b7cf387-e5f6-4c9f-b7a2-d11ff03ea446.png) still now working

.... Did you change container_image in docker-compose.yaml file?  Instead of asking me every steps，you should go to read docker docs first.

**Comment by BeastAnimation361** [comment]
![image](https://user-images.githubusercontent.com/108323892/235301343-0ca1050f-6557-466d-a843-6151b6650498.png)
there is no container_image 
so i used docker build . -t beastleechbot
and then changed 
![image](https://user-images.githubusercontent.com/108323892/235301620-e350dff7-019e-4193-947f-009cf2aa66b3.png)
and still not working
and used docker-compose up -d beastleechbot

![image](https://user-images.githubusercontent.com/108323892/235301677-130d04cb-f4c0-4291-b0d7-133ec761e3e9.png)

**Comment by wy580477** [comment]
>  there is no container_image 

....... change image: ......................................................

I'm kinda of speechless now.

**Comment by BeastAnimation361** [comment]
> container_image

yoooo come on now thats on you...container_image  i though was a variable

**Comment by BeastAnimation361** [comment]
yoooo ok soo now it's showing up
![image](https://user-images.githubusercontent.com/108323892/235301880-d10b9f4f-3ac2-4618-a4fe-9ef061ee4ebc.png)
but 
![image](https://user-images.githubusercontent.com/108323892/235301895-a8a56d68-b351-4fd3-9344-2ff71f36b929.png)

**Comment by BeastAnimation361** [comment]
bro i did missed something again? please reply.

**Comment by wy580477** [comment]
> bro i did missed something again? please reply.

go to logs folder, look at ttyd log.

**Comment by BeastAnimation361** [comment]
```
cp: can't stat '/workdir/bashrc': No such file or directory
[2023/04/29 20:11:12:0084] N: ttyd 1.7.2 (libwebsockets 4.3.2)
[2023/04/29 20:11:12:0085] N: tty configuration:
[2023/04/29 20:11:12:0085] N:   start command: bash --rcfile /mnt/data/config/bashrc
[2023/04/29 20:11:12:0085] N:   close signal: SIGHUP (1)
[2023/04/29 20:11:12:0085] N:   terminal type: xterm-256color
[2023/04/29 20:11:12:0097] N:    /usr/lib/libwebsockets-evlib_uv.so
[2023/04/29 20:11:12:0098] N: lws_create_context: LWS: 4.3.2, NET CLI SRV H1 H2 WS ConMon IPV6-off
[2023/04/29 20:11:12:0274] N: elops_init_pt_uv:  Using foreign event loop...
[2023/04/29 20:11:12:0275] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2023/04/29 20:11:12:0276] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2023/04/29 20:11:12:0277] N: __lws_lc_tag:  ++ [vh|1|default|127.0.0.1|127.0.0.1|61808] (2)
[2023/04/29 20:11:12:0280] N: [vh|1|default|127.0.0.1|127.0.0.1|61808]: lws_socket_bind: source ads 127.0.0.1
[2023/04/29 20:11:12:0281] N: __lws_lc_tag:  ++ [wsi|1|listen|default|127.0.0.1|61808] (2)
[2023/04/29 20:11:12:0281] N:  Listening on port: 61808

```

**Comment by wy580477** [comment]
> ```
> cp: can't stat '/workdir/bashrc': No such file or directory

Add bashrc file to content folder or delete --rcfile /mnt/data/config/bashrc from exec ttyd command.

Then rebuild container image and recreate container.

**Comment by BeastAnimation361** [comment]
> --rcfile /mnt/data/config/bashrc

roger that

**Comment by wy580477** [comment]
> > Then rebuild container image and recreate container.

You need to **rebuild** image and **recreate** container. 

Must use --force-recreate flag for "docker-compose up -d" command

**Comment by BeastAnimation361** [comment]
> Must use --force-recreate flag for "docker-compose up -d" command
 same error i used 
 docker build . -t beastleechbot
 docker-compose up -d  --force-recreate flag

**Comment by wy580477** [comment]
docker-compose up -d --force-recreate, not docker-compose up -d --force-recreate flag

If it still doesn't work, then I'm out of idea.

**Comment by BeastAnimation361** [comment]
oh lol yea i did that without flag.

**Comment by BeastAnimation361** [comment]
so used this cammand 
 docker build --no-cache -t beastleechbot.
and now go this
```
[2023/04/29 21:05:17:2989] N: ttyd 1.7.2 (libwebsockets 4.3.2)
[2023/04/29 21:05:17:2990] N: tty configuration:
[2023/04/29 21:05:17:2990] N:   start command: bash
[2023/04/29 21:05:17:2990] N:   close signal: SIGHUP (1)
[2023/04/29 21:05:17:2990] N:   terminal type: xterm-256color
[2023/04/29 21:05:17:3003] N:    /usr/lib/libwebsockets-evlib_uv.so
[2023/04/29 21:05:17:3004] N: lws_create_context: LWS: 4.3.2, NET CLI SRV H1 H2 WS ConMon IPV6-off
[2023/04/29 21:05:17:3165] N: elops_init_pt_uv:  Using foreign event loop...
[2023/04/29 21:05:17:3166] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2023/04/29 21:05:17:3167] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2023/04/29 21:05:17:3168] N: __lws_lc_tag:  ++ [vh|1|default|127.0.0.1|127.0.0.1|61808] (2)
[2023/04/29 21:05:17:3171] N: [vh|1|default|127.0.0.1|127.0.0.1|61808]: lws_socket_bind: source ads 127.0.0.1
[2023/04/29 21:05:17:3172] N: __lws_lc_tag:  ++ [wsi|1|listen|default|127.0.0.1|61808] (2)
[2023/04/29 21:05:17:3172] N:  Listening on port: 61808

```

**Comment by BeastAnimation361** [comment]
bro?

**Comment by wy580477** [comment]
> bro?

I'm out of idea, can't help you.

**Comment by BeastAnimation361** [comment]
```
[2023/04/29 21:05:17:2989] N: ttyd 1.7.2 (libwebsockets 4.3.2)
[2023/04/29 21:05:17:2990] N: tty configuration:
[2023/04/29 21:05:17:2990] N:   start command: bash
[2023/04/29 21:05:17:2990] N:   close signal: SIGHUP (1)
[2023/04/29 21:05:17:2990] N:   terminal type: xterm-256color
[2023/04/29 21:05:17:3003] N:    /usr/lib/libwebsockets-evlib_uv.so
[2023/04/29 21:05:17:3004] N: lws_create_context: LWS: 4.3.2, NET CLI SRV H1 H2 WS ConMon IPV6-off
[2023/04/29 21:05:17:3165] N: elops_init_pt_uv:  Using foreign event loop...
[2023/04/29 21:05:17:3166] N: __lws_lc_tag:  ++ [wsi|0|pipe] (1)
[2023/04/29 21:05:17:3167] N: __lws_lc_tag:  ++ [vh|0|netlink] (1)
[2023/04/29 21:05:17:3168] N: __lws_lc_tag:  ++ [vh|1|default|127.0.0.1|127.0.0.1|61808] (2)
[2023/04/29 21:05:17:3171] N: [vh|1|default|127.0.0.1|127.0.0.1|61808]: lws_socket_bind: source ads 127.0.0.1
[2023/04/29 21:05:17:3172] N: __lws_lc_tag:  ++ [wsi|1|listen|default|127.0.0.1|61808] (2)
[2023/04/29 21:05:17:3172] N:  Listening on port: 61808
```
this is new error now.

**Comment by wy580477** [comment]
This is no error.

Delete Caddyfile under config/caddy folder. Then run "docker exec your_container_name sv restart caddy"

**Comment by BeastAnimation361** [comment]
> This is no error.
> 
> Delete Caddyfile under config/caddy folder. Then run "docker exec your_container_name sv restart caddy"

working noww......yesss

**Comment by BeastAnimation361** [comment]
okkkk so now if i have to deply this edited redp i need toooo upload to vps and then just     docker-compose -f docker-compose_en.yml up -d ?

**Comment by wy580477** [comment]
> okkkk so now if i have to deply this edited redp i need toooo upload to vps and then just docker-compose -f docker-compose_en.yml up -d ?

You need to build your own container and change image in docker-compose file.

**Comment by BeastAnimation361** [comment]
you mean  use this cammand 
docker build . -t beastleechbot
docker-compose up -d --force-recreate

**Comment by wy580477** [comment]
> you mean use this cammand docker build . -t beastleechbot docker-compose up -d --force-recreate ofc with edits files uploaded

Please stop asking me about basic docker commands. You can learn by reading docker docs. I'm done with this thread.

**Comment by BeastAnimation361** [comment]
ok g love u bro (no homo)
