### ISSUE TITLE
Unable to mount getting this error

### ISSUE THREAD

**Issue by BeastAnimation361** [wy580477/Leech-AIO-APP-EX#95]
![image](https://user-images.githubusercontent.com/108323892/236813670-60b622af-992f-4360-a18e-e10e27e84d83.png)

**Comment by wy580477** [comment]
Running rclone mount inside container is very complex. I would rather run another rclone outside the container.

You can try to add following options to container. I don't whether this would work since I jhaven't tried to run rclone mount inside container.

    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --security-opt apparmor:unconfined \
